# Generated by Django 5.2.6 on 2025-09-05 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя интервьюера', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Фамилия интервьюера', max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, help_text='Отчество интервьюера (необязательно)', max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(help_text='Email адрес интервьюера', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('calendar_link', models.URLField(blank=True, help_text='Публичная ссылка на календарь интервьюера', verbose_name='Ссылка на календарь')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли интервьюер для проведения интервью', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Интервьюер',
                'verbose_name_plural': 'Интервьюеры',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
