# Generated by Django 5.2.6 on 2025-09-12 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_salaryrange'),
    ]

    operations = [
    ]
