# Generated by Django 5.2.6 on 2025-09-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20250912_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='screening_duration',
            field=models.PositiveIntegerField(default=45, help_text='Длительность скринингов в минутах', verbose_name='Длительность скринингов (минуты)'),
        ),
    ]
