# Generated by Django 5.2.6 on 2025-09-16 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_grades'),
        ('vacancies', '0005_salaryrange_vacancy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salaryrange',
            unique_together={('vacancy', 'grade')},
        ),
    ]
