# Generated by Django 5.2.5 on 2025-10-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_add_eur_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryrange',
            name='salary_max_eur',
        ),
        migrations.RemoveField(
            model_name='salaryrange',
            name='salary_min_eur',
        ),
    ]
