# Generated by Django 5.2.5 on 2025-10-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_remove_salaryrange_salary_max_eur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrange',
            name='salary_max_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная зарплата в евро', max_digits=12, null=True, verbose_name='Максимальная зарплата (EUR)'),
        ),
        migrations.AddField(
            model_name='salaryrange',
            name='salary_min_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная зарплата в евро', max_digits=12, null=True, verbose_name='Минимальная зарплата (EUR)'),
        ),
    ]
