# Generated by Django 5.2.5 on 2025-10-16 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_add_stage_fields_and_remove_invite_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('bulk_update', 'Массовое обновление'), ('single_update', 'Обновление одного скоркарда')], default='bulk_update', max_length=20, verbose_name='Тип операции')),
                ('updated_count', models.PositiveIntegerField(verbose_name='Количество обновленных скоркардов')),
                ('total_found', models.PositiveIntegerField(verbose_name='Всего найдено скоркардов')),
                ('date_range_from', models.DateField(verbose_name='Период с')),
                ('date_range_to', models.DateField(verbose_name='Период по')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Ошибки')),
                ('updated_interviews', models.JSONField(blank=True, default=list, verbose_name='Обновленные интервью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_updates', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'История обновления скоркардов',
                'verbose_name_plural': 'История обновлений скоркардов',
                'ordering': ['-created_at'],
            },
        ),
    ]
