# Generated by Django 4.2.16 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_scorecardupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='technologies',
            field=models.TextField(blank=True, help_text='Список технологий через запятую (например: Python, Django, PostgreSQL, Redis)', verbose_name='Технологии'),
        ),
    ]
