# Generated by Django 4.2.16 on 2025-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_vacancy_mandatory_tech_interviewers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='tech_invite_text',
            field=models.TextField(blank=True, help_text='Текст сопроводительного письма для приглашений на технические интервью', verbose_name='Сопровождающий текст для инвайтов на тех. интервью'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_invite_title',
            field=models.CharField(blank=True, help_text='Заголовок для приглашений на технические интервью', max_length=200, verbose_name='Заголовок инвайтов на тех. интервью'),
        ),
    ]
