# Generated by Django 5.2.5 on 2025-10-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_vacancy_tech_invite_text_vacancy_tech_invite_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Автоматически определяется на основе активных заявок на найм', verbose_name='Активна'),
        ),
    ]
