# Generated by Django 5.2.5 on 2025-10-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_alter_vacancy_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalaryRange',
        ),
    ]
