# Generated by Django 5.2.5 on 2025-09-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='PLNTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Подоходный налог, Социальные взносы', max_length=100, verbose_name='Название налога')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Процент от 0 до 100', max_digits=5, verbose_name='Налоговая ставка (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли налог в расчетах', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Налог PLN',
                'verbose_name_plural': 'Налоги PLN',
                'ordering': ('name',),
            },
        ),
    ]
