# Generated by Django 5.2.5 on 2025-09-18 18:38

from django.db import migrations, models


def migrate_amount_to_salary_range(apps, schema_editor):
    """Переносит данные из поля amount в salary_from и salary_to"""
    Benchmark = apps.get_model('finance', 'Benchmark')
    
    for benchmark in Benchmark.objects.all():
        # Для кандидатов: amount -> salary_from, salary_to = None
        if benchmark.type == 'candidate':
            benchmark.salary_from = benchmark.amount
            benchmark.salary_to = None
        # Для вакансий: amount -> salary_from, salary_to = None (пока что)
        else:
            benchmark.salary_from = benchmark.amount
            benchmark.salary_to = None
        benchmark.save()


def reverse_migrate_salary_range_to_amount(apps, schema_editor):
    """Обратный перенос данных из salary_from в amount"""
    Benchmark = apps.get_model('finance', 'Benchmark')
    
    for benchmark in Benchmark.objects.all():
        benchmark.amount = benchmark.salary_from
        benchmark.save()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_benchmark_work_format'),
    ]

    operations = [
        # Добавляем новые поля
        migrations.AddField(
            model_name='benchmark',
            name='salary_from',
            field=models.DecimalField(
                decimal_places=2, 
                default=0, 
                help_text='Минимальная зарплата в USD (для кандидатов - их зарплата)', 
                max_digits=12, 
                verbose_name='Зарплата от'
            ),
        ),
        migrations.AddField(
            model_name='benchmark',
            name='salary_to',
            field=models.DecimalField(
                blank=True, 
                decimal_places=2, 
                help_text='Максимальная зарплата в USD (только для вакансий)', 
                max_digits=12, 
                null=True, 
                verbose_name='Зарплата до'
            ),
        ),
        
        # Переносим данные
        migrations.RunPython(
            migrate_amount_to_salary_range,
            reverse_migrate_salary_range_to_amount,
        ),
        
        # Удаляем старое поле
        migrations.RemoveField(
            model_name='benchmark',
            name='amount',
        ),
    ]
