# Generated by Django 5.2.5 on 2025-09-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_benchmarksettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarksettings',
            name='gemini_api_key',
        ),
    ]
