# Generated by Django 5.2.5 on 2025-11-03 21:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название страницы вики', max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL (например: "nastroyki-kompanii"). Используется для создания URL страницы', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('content', models.TextField(help_text='Основной текст страницы вики (поддерживает Markdown)', validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Содержание')),
                ('description', models.TextField(blank=True, help_text='Краткое описание страницы для превью', max_length=500, verbose_name='Краткое описание')),
                ('category', models.CharField(blank=True, help_text='Категория страницы (например: "Настройки", "Функциональность", "Интеграции")', max_length=50, verbose_name='Категория')),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения страницы в списке (меньше = выше)', verbose_name='Порядок сортировки')),
                ('is_published', models.BooleanField(default=True, help_text='Показывать ли страницу в списке', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, help_text='Пользователь, создавший страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='Пользователь, последним отредактировавший страницу', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_wiki_pages', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор')),
            ],
            options={
                'verbose_name': 'Страница вики',
                'verbose_name_plural': 'Страницы вики',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='WikiPageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('change_note', models.CharField(blank=True, help_text='Краткое описание внесенных изменений', max_length=200, verbose_name='Примечание к изменению')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_edits', to=settings.AUTH_USER_MODEL, verbose_name='Редактор')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='wiki.wikipage', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'История изменений страницы',
                'verbose_name_plural': 'История изменений страниц',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['slug'], name='wiki_wikipa_slug_f0f6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='wikipage',
            index=models.Index(fields=['category', 'is_published'], name='wiki_wikipa_categor_8890c6_idx'),
        ),
    ]
