# Generated by Django 5.2.5 on 2025-11-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега (например: "настройка", "вакансии", "интеграции")', max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='#6c757d', help_text='Цвет тега в формате HEX (например: #007bff)', max_length=7, verbose_name='Цвет тега')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тег вики',
                'verbose_name_plural': 'Теги вики',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='wikipage',
            name='related_app',
            field=models.CharField(blank=True, choices=[('', 'Не привязано'), ('accounts', 'Пользователи'), ('company_settings', 'Настройки компании'), ('finance', 'Финансы'), ('vacancies', 'Вакансии'), ('hiring_plan', 'План найма'), ('google_oauth', 'Google Calendar'), ('gemini', 'AI-помощник'), ('interviewers', 'Интервьюеры'), ('clickup_int', 'ClickUp'), ('notion_int', 'Notion'), ('huntflow', 'Huntflow')], default='', help_text='Приложение, к которому относится страница', max_length=50, verbose_name='Связанное приложение'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Теги (метки) для страницы', related_name='pages', to='wiki.wikitag', verbose_name='Теги'),
        ),
    ]
