# Generated by Django 5.2.6 on 2025-09-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0003_make_date_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickuptask',
            name='custom_fields',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Дополнительные поля задачи в формате JSON',
                verbose_name='Дополнительные поля'
            ),
        ),
    ]
