# Generated by Django 5.2.6 on 2025-09-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0004_add_custom_fields'),
    ]

    operations = [
    ]
