# Generated by Django 5.2.5 on 2025-11-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikitag_wikipage_related_app_wikipage_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipage',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Без категории'), ('Введение', 'Введение'), ('Архитектура', 'Архитектура'), ('Настройка', 'Настройка'), ('Использование', 'Использование'), ('Интеграции', 'Интеграции')], default='', help_text='Категория страницы', max_length=50, verbose_name='Категория'),
        ),
    ]
