# Generated by Django 5.2.5 on 2025-09-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_clickup_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notion_integration_token',
            field=models.CharField(blank=True, max_length=256, verbose_name='Integration токен Notion'),
        ),
    ]
