# Generated by Django 5.2.5 on 2025-10-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='huntflow_access_token',
            field=models.CharField(blank=True, help_text='Access token для Huntflow API', max_length=1000, verbose_name='Access token для Huntflow API'),
        ),
        migrations.AlterField(
            model_name='user',
            name='huntflow_refresh_token',
            field=models.CharField(blank=True, help_text='Refresh token для Huntflow API', max_length=1000, verbose_name='Refresh token для Huntflow API'),
        ),
    ]
