# Generated by Django 5.2.6 on 2025-09-05 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100, unique=True, verbose_name='Google ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='URL фото')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(verbose_name='Токен истекает')),
                ('scopes', models.JSONField(default=list, verbose_name='Разрешения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google OAuth аккаунт',
                'verbose_name_plural': 'Google OAuth аккаунты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, verbose_name='ID файла')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('mime_type', models.CharField(max_length=200, verbose_name='Тип MIME')),
                ('size', models.BigIntegerField(blank=True, null=True, verbose_name='Размер (байт)')),
                ('created_time', models.DateTimeField(verbose_name='Создано')),
                ('modified_time', models.DateTimeField(verbose_name='Изменено')),
                ('web_view_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для просмотра')),
                ('web_content_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для скачивания')),
                ('parents', models.JSONField(default=list, verbose_name='Родительские папки')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_files', to='google_oauth.googleoauthaccount')),
            ],
            options={
                'verbose_name': 'Файл Google Drive',
                'verbose_name_plural': 'Файлы Google Drive',
                'ordering': ['-modified_time'],
                'unique_together': {('google_account', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=200, verbose_name='ID события')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('all_day', models.BooleanField(default=False, verbose_name='Весь день')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Местоположение')),
                ('status', models.CharField(default='confirmed', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('google_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Создано в Google')),
                ('google_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Обновлено в Google')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='google_oauth.googleoauthaccount')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['-start_time'],
                'unique_together': {('google_account', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(max_length=200, verbose_name='ID таблицы')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('created_time', models.DateTimeField(verbose_name='Создано')),
                ('modified_time', models.DateTimeField(verbose_name='Изменено')),
                ('web_view_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для просмотра')),
                ('synced_at', models.DateTimeField(auto_now_add=True, verbose_name='Синхронизировано')),
                ('google_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='google_oauth.googleoauthaccount')),
            ],
            options={
                'verbose_name': 'Google Таблица',
                'verbose_name_plural': 'Google Таблицы',
                'ordering': ['-modified_time'],
                'unique_together': {('google_account', 'spreadsheet_id')},
            },
        ),
    ]
