# Generated by Django 5.2.5 on 2025-09-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0005_scorecardpathsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID события в Google Calendar'),
        ),
        migrations.AddField(
            model_name='invite',
            name='calendar_event_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на событие в Google Calendar'),
        ),
    ]
