# Generated by Django 5.2.5 on 2025-09-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0009_invite_gemini_additional_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='original_form_data',
            field=models.TextField(blank=True, help_text='Весь текст, введенный пользователем в комбинированную форму', verbose_name='Исходные данные из формы'),
        ),
    ]
