# Generated by Django 5.2.5 on 2025-09-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0012_hrscreening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrscreening',
            name='status',
        ),
    ]
