# Generated by Django 5.2.5 on 2025-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0013_remove_hrscreening_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('belarus', 'Беларусь'), ('poland', 'Польша')], max_length=20, unique=True, verbose_name='Страна')),
                ('questions', models.TextField(help_text='Вопросы для данной страны, разделенные переносами строк', verbose_name='Вопросы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон вопросов',
                'verbose_name_plural': 'Шаблоны вопросов',
            },
        ),
    ]
