# Generated by Django 5.2.6 on 2025-09-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0014_questiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrscreening',
            name='determined_grade',
            field=models.CharField(blank=True, help_text='Грейд, определенный на основе зарплатных вилок', max_length=100, verbose_name='Определенный грейд'),
        ),
        migrations.AddField(
            model_name='hrscreening',
            name='extracted_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Первое числовое значение из поля Зарплата', max_digits=10, null=True, verbose_name='Извлеченная зарплата'),
        ),
        migrations.AddField(
            model_name='hrscreening',
            name='huntflow_grade_id',
            field=models.CharField(blank=True, help_text='ID грейда в системе Huntflow', max_length=50, verbose_name='ID грейда в Huntflow'),
        ),
        migrations.AddField(
            model_name='hrscreening',
            name='salary_currency',
            field=models.CharField(default='USD', help_text='Валюта зарплаты (по умолчанию USD)', max_length=3, verbose_name='Валюта зарплаты'),
        ),
    ]
