# Generated by Django 4.2.16 on 2025-10-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0016_alter_hrscreening_huntflow_grade_id_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название чата'),
        ),
    ]
