# Generated by Django 5.2.5 on 2025-10-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0017_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='multiple_slots_data',
            field=models.JSONField(blank=True, default=dict, help_text='Информация о множественных временных слотах кандидата и совпадениях', verbose_name='Данные множественных слотов'),
        ),
    ]
