# Generated by Django 5.2.5 on 2025-10-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0020_auto_20251015_0133'),
    ]

    operations = [
        # Поле multiple_slots_data уже удалено из модели, операция не нужна
    ]
