# Generated by Django 5.2.5 on 2025-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0023_chatsession_vacancy'),
    ]

    operations = [
        # Поле multiple_slots_data уже удалено из модели, операция не нужна
        migrations.AddField(
            model_name='invite',
            name='custom_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано, будет использоваться вместо стандартной длительности из вакансии', null=True, verbose_name='Кастомная длительность встречи (минуты)'),
        ),
    ]
