# Generated by Django 5.2.5 on 2025-10-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0025_add_user_email_to_invite'),
        ('google_oauth', '0025_remove_invite_multiple_slots_data_invite_user_email'),
    ]

    operations = [
    ]
