# Generated by Django 5.2.5 on 2025-10-22 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0027_remove_invite_multiple_slots_data'),
        ('interviewers', '0004_remove_interviewrule_allow_holiday_interviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='interviewer',
            field=models.ForeignKey(blank=True, help_text='Интервьюер, назначенный для проведения интервью', null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewers.interviewer', verbose_name='Интервьюер'),
        ),
    ]
