# Generated by Django 5.2.5 on 2025-11-03 19:35

from django.db import migrations, models


def update_hr_screening_to_hrscreening(apps, schema_editor):
    """Обновляет существующие записи с типом 'hr_screening' на 'hrscreening'"""
    ChatMessage = apps.get_model('google_oauth', 'ChatMessage')
    ChatMessage.objects.filter(message_type='hr_screening').update(message_type='hrscreening')


def reverse_update(apps, schema_editor):
    """Обратная операция - обновляет 'hrscreening' обратно на 'hr_screening'"""
    ChatMessage = apps.get_model('google_oauth', 'ChatMessage')
    ChatMessage.objects.filter(message_type='hrscreening').update(message_type='hr_screening')


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0028_add_interviewer_to_invite'),
    ]

    operations = [
        migrations.RunPython(update_hr_screening_to_hrscreening, reverse_update),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user', 'Пользователь'), ('system', 'Система'), ('hrscreening', 'HR-скрининг'), ('invite', 'Инвайт')], max_length=20, verbose_name='Тип сообщения'),
        ),
    ]
