# Generated by Django 5.2.5 on 2025-09-20 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('session_name', models.CharField(max_length=100, unique=True, verbose_name='Имя сессии')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Авторизован')),
                ('auth_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата авторизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram пользователь',
                'verbose_name_plural': 'Telegram пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuthAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('qr', 'QR Code'), ('phone', 'Phone'), ('2fa', 'Two Factor Auth')], max_length=20, verbose_name='Тип попытки')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('timeout', 'Таймаут')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_attempts', to='telegram.telegramuser', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Попытка авторизации',
                'verbose_name_plural': 'Попытки авторизации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('chat_id', models.BigIntegerField(verbose_name='ID чата')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
                ('date', models.DateTimeField(verbose_name='Дата сообщения')),
                ('is_outgoing', models.BooleanField(default=False, verbose_name='Исходящее')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='telegram.telegramuser', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Telegram сообщение',
                'verbose_name_plural': 'Telegram сообщения',
                'ordering': ['-date'],
                'unique_together': {('telegram_user', 'message_id', 'chat_id')},
            },
        ),
    ]
