# Generated by Django 5.2.6 on 2025-09-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_grades'),
        ('interviewers', '0002_interviewrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewrule',
            options={'ordering': ['min_grade__name', 'name'], 'verbose_name': 'Правило привлечения интервьюеров', 'verbose_name_plural': 'Правила привлечения интервьюеров'},
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='interview_type',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='max_advance_notice_hours',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='min_advance_notice_hours',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='priority',
        ),
        migrations.AlterField(
            model_name='interviewrule',
            name='max_grade',
            field=models.ForeignKey(help_text='Максимальный грейд для привлечения интервьюера', on_delete=django.db.models.deletion.CASCADE, related_name='interview_rules_max', to='finance.grade', verbose_name='Максимальный грейд'),
        ),
        migrations.AlterField(
            model_name='interviewrule',
            name='min_grade',
            field=models.ForeignKey(help_text='Минимальный грейд для привлечения интервьюера', on_delete=django.db.models.deletion.CASCADE, related_name='interview_rules_min', to='finance.grade', verbose_name='Минимальный грейд'),
        ),
    ]
