# Generated by Django 5.2.6 on 2025-09-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevent',
            name='attendees',
            field=models.JSONField(blank=True, default=list, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='creator_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email создателя'),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='creator_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя создателя'),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='meet_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Google Meet'),
        ),
    ]
