# Generated by Django 5.2.6 on 2025-09-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0003_invite_syncsettings'),
    ]

    operations = [
        # Удаляем модели для хранения API данных - теперь данные кэшируются в Redis
        migrations.DeleteModel(
            name='GoogleCalendarEvent',
        ),
        migrations.DeleteModel(
            name='GoogleDriveFile',
        ),
        migrations.DeleteModel(
            name='GoogleSheet',
        ),
    ]
