# Generated by Django 5.2.5 on 2025-09-11 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0011_remove_invite_gemini_additional_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Текст, введенный пользователем для HR-скрининга', verbose_name='Исходные данные')),
                ('candidate_url', models.URLField(blank=True, help_text='Ссылка на кандидата в Huntflow', verbose_name='Ссылка на кандидата')),
                ('candidate_id', models.CharField(blank=True, max_length=50, verbose_name='ID кандидата')),
                ('vacancy_id', models.CharField(blank=True, max_length=50, verbose_name='ID вакансии')),
                ('candidate_name', models.CharField(blank=True, max_length=255, verbose_name='Имя кандидата')),
                ('candidate_grade', models.CharField(blank=True, max_length=100, verbose_name='Уровень кандидата')),
                ('vacancy_title', models.CharField(blank=True, max_length=255, verbose_name='Название вакансии')),
                ('gemini_analysis', models.TextField(blank=True, help_text='JSON ответ от Gemini AI с данными для обновления кандидата', verbose_name='Анализ от Gemini AI')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_screenings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'HR-скрининг',
                'verbose_name_plural': 'HR-скрининги',
                'ordering': ['-created_at'],
            },
        ),
    ]
