# Generated by Django 5.2.6 on 2025-09-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviewers', '0004_remove_interviewrule_allow_holiday_interviews_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название вакансии', max_length=200, verbose_name='Название вакансии')),
                ('external_id', models.CharField(help_text='Внешний идентификатор для связи с внешними системами', max_length=100, unique=True, verbose_name='ID для связи')),
                ('invite_title', models.CharField(help_text='Заголовок для приглашений кандидатов', max_length=200, verbose_name='Заголовок инвайтов')),
                ('invite_text', models.TextField(help_text='Текст сопроводительного письма для приглашений', verbose_name='Сопровождающий текст для инвайтов')),
                ('scorecard_title', models.CharField(help_text='Заголовок для Scorecard', max_length=200, verbose_name='Заголовок Scorecard')),
                ('scorecard_link', models.URLField(blank=True, help_text='Ссылка на Scorecard для оценки кандидатов', verbose_name='Ссылка на Scorecard')),
                ('questions_belarus', models.TextField(blank=True, help_text='Вопросы для интервью в Беларуси', verbose_name='Вопросы Беларусь')),
                ('questions_poland', models.TextField(blank=True, help_text='Вопросы для интервью в Польше', verbose_name='Вопросы Польша')),
                ('candidate_update_prompt', models.TextField(blank=True, help_text='Промпт для обновления информации о кандидате', verbose_name='Промпт для обновления кандидата')),
                ('invite_prompt', models.TextField(blank=True, help_text='Промпт для создания приглашения кандидату', verbose_name='Промпт для инвайта')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли вакансия', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('interviewers', models.ManyToManyField(blank=True, help_text='Интервьюеры, привязанные к вакансии', related_name='vacancies', to='interviewers.interviewer', verbose_name='Интервьюеры')),
                ('recruiter', models.ForeignKey(help_text='Рекрутер, ответственный за вакансию', limit_choices_to={'groups__name': 'Рекрутер'}, on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный рекрутер')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
    ]
