# Generated by Django 5.2.6 on 2025-09-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_add_screening_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrange',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text='Вакансия для которой устанавливается зарплатная вилка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_ranges', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
