# Generated by Django 5.2.6 on 2025-09-16 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_salaryrange_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrange',
            name='vacancy',
            field=models.ForeignKey(help_text='Вакансия для которой устанавливается зарплатная вилка', on_delete=django.db.models.deletion.CASCADE, related_name='salary_ranges', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
