# Generated by Django 5.2.6 on 2025-09-19 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_vacancy_link_belarus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_link_remote',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_link_russia',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_link_ukraine',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy_link_usa',
        ),
    ]
