# Generated by Django 5.2.5 on 2025-10-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_add_eur_fields_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='invite_prompt',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hr_screening_stage',
            field=models.CharField(blank=True, help_text='Этап в Huntflow, на который переводить кандидата после HR-скрининга', max_length=100, verbose_name='Этап после HR-скрининга'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_interview_stage',
            field=models.CharField(blank=True, help_text='Этап в Huntflow, на который переводить кандидата после Tech-интервью', max_length=100, verbose_name='Этап после Tech-интервью'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_screening_stage',
            field=models.CharField(blank=True, help_text='Этап в Huntflow, на который переводить кандидата после Tech-скрининга', max_length=100, verbose_name='Этап после Tech-скрининга'),
        ),
    ]
