# Generated by Django 4.2.16 on 2025-10-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0004_remove_interviewrule_allow_holiday_interviews_and_more'),
        ('vacancies', '0016_vacancy_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='mandatory_tech_interviewers',
            field=models.ManyToManyField(blank=True, help_text='Интервьюеры, которые обязательно должны участвовать в техническом интервью', related_name='mandatory_tech_interviews', to='interviewers.interviewer', verbose_name='Обязательные участники тех. интервью'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='tech_interview_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность технического интервью в минутах', null=True, verbose_name='Длительность тех. интервью (минуты)'),
        ),
    ]
