# Generated by Django 5.2.5 on 2025-09-18 16:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_calculation_period_days', models.PositiveIntegerField(default=90, help_text='Количество дней для расчета средних значений бенчмарков', verbose_name='Период расчета среднего (дни)')),
                ('belarus_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('13.00'), help_text='Налоговая ставка в Беларуси для пересчета net/gross', max_digits=5, verbose_name='Налог в РБ (%)')),
                ('ai_analysis_prompt', models.TextField(default='Проанализируй данные о зарплатах и предоставь статистику по рынку труда.', help_text='Промпт для анализа данных о зарплатах через ИИ', verbose_name='Промпт для анализа данных через ИИ')),
                ('data_sources', models.JSONField(default=list, help_text='Список активных источников данных о вакансиях', verbose_name='Источники данных о вакансиях')),
                ('max_daily_tasks', models.PositiveIntegerField(default=100, help_text='Максимальное количество задач для обработки в день', verbose_name='Максимальное количество задач в день')),
                ('vacancy_fields', models.JSONField(default=list, help_text='Список полей для сохранения информации о вакансиях', verbose_name='Поля для сохранения вакансий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки бенчмарков',
                'verbose_name_plural': 'Настройки бенчмарков',
            },
        ),
    ]
