# Generated by Django 5.2.5 on 2025-10-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_remove_benchmarksettings_gemini_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrange',
            name='salary_max_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная зарплата в евро', max_digits=12, null=True, verbose_name='Максимальная зарплата (EUR)'),
        ),
        migrations.AddField(
            model_name='salaryrange',
            name='salary_min_eur',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная зарплата в евро', max_digits=12, null=True, verbose_name='Минимальная зарплата (EUR)'),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='code',
            field=models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('PLN', 'PLN'), ('EUR', 'EUR')], max_length=3, unique=True, verbose_name='Код валюты'),
        ),
    ]
