# Generated by Django 4.2.16 on 2025-10-23 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0015_scorecardupdatehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0019_add_eur_currency_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название плана найма', max_length=255, verbose_name='Название плана')),
                ('description', models.TextField(blank=True, help_text='Подробное описание плана найма', verbose_name='Описание')),
                ('start_date', models.DateField(help_text='Дата начала плана найма', verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Планируемая дата окончания плана', null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'На паузе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', help_text='Текущий статус плана найма', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner', models.ForeignKey(help_text='Пользователь, создавший план', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hiring_plans', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('responsible_recruiter', models.ForeignKey(help_text='Рекрутер, ответственный за выполнение плана', limit_choices_to={'groups__name': 'Рекрутер'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_hiring_plans', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный рекрутер')),
            ],
            options={
                'verbose_name': 'План найма',
                'verbose_name_plural': 'Планы найма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_positions', models.PositiveIntegerField(default=0, help_text='Общее количество позиций в плане', verbose_name='Всего позиций')),
                ('total_headcount_needed', models.PositiveIntegerField(default=0, help_text='Общее количество требуемых специалистов', verbose_name='Всего требуется')),
                ('total_headcount_hired', models.PositiveIntegerField(default=0, help_text='Общее количество нанятых специалистов', verbose_name='Всего нанято')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Процент выполнения плана найма', max_digits=5, verbose_name='Процент выполнения')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Дата последнего обновления метрик', verbose_name='Последнее обновление')),
                ('hiring_plan', models.OneToOneField(help_text='План найма, для которого рассчитываются метрики', on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='hiring_plan.hiringplan', verbose_name='План найма')),
            ],
            options={
                'verbose_name': 'Метрики плана найма',
                'verbose_name_plural': 'Метрики планов найма',
            },
        ),
        migrations.CreateModel(
            name='HiringPlanPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount_needed', models.PositiveIntegerField(help_text='Количество специалистов, которое нужно нанять', verbose_name='Требуется специалистов')),
                ('headcount_hired', models.PositiveIntegerField(default=0, help_text='Количество уже нанятых специалистов', verbose_name='Нанято специалистов')),
                ('headcount_in_progress', models.PositiveIntegerField(default=0, help_text='Количество специалистов, найм которых в процессе', verbose_name='В процессе найма')),
                ('priority', models.IntegerField(choices=[(1, 'Критический'), (2, 'Высокий'), (3, 'Средний'), (4, 'Низкий')], default=3, help_text='Приоритет позиции в плане', verbose_name='Приоритет')),
                ('urgency_deadline', models.DateField(blank=True, help_text='Критический дедлайн для закрытия позиции', null=True, verbose_name='Дедлайн')),
                ('specifics', models.TextField(blank=True, help_text='Особые требования и специфика позиции', verbose_name='Специфика позиции')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки по позиции', verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли позиция в плане', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grades', models.ManyToManyField(blank=True, help_text='Требуемые грейды специалистов', to='finance.grade', verbose_name='Грейды')),
                ('hiring_plan', models.ForeignKey(help_text='План найма, к которому относится позиция', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hiring_plan.hiringplan', verbose_name='План найма')),
                ('vacancy', models.ForeignKey(help_text='Вакансия для данной позиции', on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Позиция в плане найма',
                'verbose_name_plural': 'Позиции в планах найма',
                'ordering': ['priority', 'urgency_deadline'],
                'unique_together': {('hiring_plan', 'vacancy')},
            },
        ),
    ]
