# Generated by Django 4.2.16 on 2025-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hiringplanposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='project',
            field=models.CharField(blank=True, help_text='Название проекта, для которого нужна позиция', max_length=200, verbose_name='Проект'),
        ),
    ]
