# Generated by Django 5.2.5 on 2025-10-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0002_alter_hiringplanposition_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPeriodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Месячный план'), ('quarterly', 'Квартальный план'), ('yearly', 'Годовой план'), ('custom', 'Кастомный период')], help_text='Тип периода плана', max_length=20, unique=True, verbose_name='Тип периода')),
                ('name', models.CharField(help_text='Название типа периода', max_length=100, verbose_name='Название')),
                ('days', models.IntegerField(help_text='Количество дней в периоде', verbose_name='Количество дней')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли тип периода', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип периода',
                'verbose_name_plural': 'Типы периодов',
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='PositionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('current', 'Текущая работа'), ('replacement', 'Замена сотрудника'), ('planned', 'Плановая позиция'), ('urgent', 'Срочная позиция'), ('potential', 'Потенциальная позиция')], help_text='Тип позиции в плане найма', max_length=20, unique=True, verbose_name='Тип позиции')),
                ('name', models.CharField(help_text='Название типа позиции', max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Описание типа позиции', verbose_name='Описание')),
                ('priority_boost', models.IntegerField(default=0, help_text='Добавляет приоритет к позиции', verbose_name='Бонус приоритета')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли тип позиции', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип позиции',
                'verbose_name_plural': 'Типы позиций',
                'ordering': ['priority_boost', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hiringplan',
            name='is_auto_generated',
            field=models.BooleanField(default=False, help_text='Автоматически созданный план', verbose_name='Автоматически созданный'),
        ),
        migrations.AddField(
            model_name='hiringplan',
            name='parent_plan',
            field=models.ForeignKey(blank=True, help_text='Родительский план (если это перенесенные позиции)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.hiringplan', verbose_name='Родительский план'),
        ),
        migrations.AddField(
            model_name='hiringplan',
            name='previous_plan',
            field=models.ForeignKey(blank=True, help_text='Предыдущий план', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_plans', to='hiring_plan.hiringplan', verbose_name='Предыдущий план'),
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='filled_date',
            field=models.DateField(blank=True, help_text='Дата закрытия позиции', null=True, verbose_name='Дата закрытия позиции'),
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='replaced_employee_id',
            field=models.CharField(blank=True, help_text='ID заменяемого сотрудника (из системы)', max_length=100, verbose_name='ID заменяемого сотрудника'),
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='replacement_reason',
            field=models.CharField(blank=True, help_text='Причина замены сотрудника', max_length=200, verbose_name='Причина замены'),
        ),
        migrations.AddField(
            model_name='hiringplan',
            name='period_type',
            field=models.ForeignKey(blank=True, help_text='Тип периода плана', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.planperiodtype', verbose_name='Тип периода'),
        ),
        migrations.CreateModel(
            name='PositionKPIOKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название KPI/OKR', max_length=255, verbose_name='Название')),
                ('metric_type', models.CharField(choices=[('kpi', 'KPI'), ('okr', 'OKR'), ('custom', 'Кастомная метрика')], help_text='Тип метрики', max_length=20, verbose_name='Тип метрики')),
                ('description', models.TextField(blank=True, help_text='Описание метрики', verbose_name='Описание')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Целевое значение метрики', max_digits=10, verbose_name='Целевое значение')),
                ('unit', models.CharField(default='%', help_text='Единица измерения', max_length=50, verbose_name='Единица измерения')),
                ('sla_value', models.DecimalField(blank=True, decimal_places=2, help_text='Значение по SLA для сравнения', max_digits=10, null=True, verbose_name='SLA значение')),
                ('sla_comparison', models.CharField(blank=True, help_text='Например: "120% от SLA" или "требуется улучшение"', max_length=50, verbose_name='Сравнение с SLA')),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, help_text='Фактическое значение метрики', max_digits=10, null=True, verbose_name='Фактическое значение')),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('in_progress', 'В процессе'), ('achieved', 'Достигнуто'), ('failed', 'Не достигнуто')], default='pending', help_text='Статус достижения метрики', max_length=20, verbose_name='Статус')),
                ('period_start', models.DateField(help_text='Начало периода для метрики', verbose_name='Начало периода')),
                ('period_end', models.DateField(help_text='Конец периода для метрики', verbose_name='Конец периода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grade', models.ForeignKey(blank=True, help_text='Грейд для KPI/OKR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.grade', verbose_name='Грейд')),
                ('hiring_plan', models.ForeignKey(blank=True, help_text='План найма для KPI/OKR', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_okr', to='hiring_plan.hiringplan', verbose_name='План найма')),
                ('position_type', models.ForeignKey(blank=True, help_text='Тип позиции для KPI/OKR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.positiontype', verbose_name='Тип позиции')),
            ],
            options={
                'verbose_name': 'KPI/OKR',
                'verbose_name_plural': 'KPI/OKR',
                'ordering': ['-period_start', 'metric_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='position_type',
            field=models.ForeignKey(blank=True, help_text='Тип позиции (текущая/замена/плановая)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.positiontype', verbose_name='Тип позиции'),
        ),
        migrations.CreateModel(
            name='PositionSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_time_to_fill', models.IntegerField(help_text='Целевое время закрытия вакансии в днях', verbose_name='Целевой Time-to-Fill (дни)')),
                ('target_time_to_hire', models.IntegerField(help_text='Целевое время найма в днях', verbose_name='Целевой Time-to-Hire (дни)')),
                ('median_time_to_fill', models.DecimalField(decimal_places=2, default=0, help_text='Медианное время закрытия вакансии', max_digits=6, verbose_name='Медианный Time-to-Fill')),
                ('warning_threshold_percent', models.IntegerField(default=80, help_text='Процент от SLA для предупреждения', verbose_name='Порог предупреждения (%)')),
                ('critical_threshold_percent', models.IntegerField(default=120, help_text='Процент от SLA для критического статуса', verbose_name='Критический порог (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли SLA', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grade', models.ForeignKey(blank=True, help_text='Грейд специалиста (опционально)', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд')),
                ('position_type', models.ForeignKey(help_text='Тип позиции для SLA', on_delete=django.db.models.deletion.CASCADE, to='hiring_plan.positiontype', verbose_name='Тип позиции')),
            ],
            options={
                'verbose_name': 'SLA позиции',
                'verbose_name_plural': 'SLA позиций',
                'ordering': ['position_type', 'grade'],
                'unique_together': {('position_type', 'grade')},
            },
        ),
    ]
