# Generated by Django 5.2.5 on 2025-10-23 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0003_planperiodtype_positiontype_and_more'),
        ('vacancies', '0018_vacancy_tech_invite_text_vacancy_tech_invite_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionsla',
            options={'ordering': ['vacancy', 'grade'], 'verbose_name': 'SLA вакансии', 'verbose_name_plural': 'SLA вакансий'},
        ),
        migrations.AlterUniqueTogether(
            name='positionsla',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hiringplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hiringplan',
            name='parent_plan',
        ),
        migrations.RemoveField(
            model_name='hiringplan',
            name='responsible_recruiter',
        ),
        migrations.RemoveField(
            model_name='hiringplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='hiringplan',
            name='status',
        ),
        migrations.AddField(
            model_name='hiringplan',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='План завершен', verbose_name='Завершен'),
        ),
        migrations.AddField(
            model_name='positionkpiokr',
            name='scope',
            field=models.CharField(choices=[('vacancy', 'Для конкретной вакансии'), ('grade', 'Для конкретного грейда'), ('vacancy_grade', 'Для вакансии + грейда'), ('plan_block', 'Блок для плана (массово)'), ('global', 'Глобальная метрика')], default='vacancy', help_text='Определяет, как применяется метрика', max_length=20, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='positionkpiokr',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text='Если scope = vacancy/vacancy_grade', null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='positionsla',
            name='vacancy',
            field=models.ForeignKey(blank=True, help_text='SLA для конкретной вакансии', null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='hiringplan',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Опционально - подтягивается автоматически', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hiring_plans', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='hiringplan',
            name='period_type',
            field=models.ForeignKey(blank=True, help_text='Месячный/Квартальный/Годовой', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.planperiodtype', verbose_name='Тип периода'),
        ),
        migrations.AlterField(
            model_name='positionkpiokr',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Если scope = grade/vacancy_grade', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд'),
        ),
        migrations.AlterField(
            model_name='positionkpiokr',
            name='hiring_plan',
            field=models.ForeignKey(blank=True, help_text='План найма для KPI/OKR', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.hiringplan', verbose_name='План найма'),
        ),
        migrations.AlterField(
            model_name='positionkpiokr',
            name='metric_type',
            field=models.CharField(choices=[('kpi', 'KPI'), ('okr', 'OKR'), ('custom', 'Custom')], help_text='Тип метрики', max_length=20, verbose_name='Тип метрики'),
        ),
        migrations.AlterField(
            model_name='positionsla',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Если NULL - SLA для всех грейдов этой вакансии', null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд'),
        ),
        migrations.CreateModel(
            name='PlanKPIOKRBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: "Backend найм Q4" или "Замены срочные"', max_length=255, verbose_name='Название блока')),
                ('description', models.TextField(blank=True, help_text='Описание блока KPI/OKR', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли блок', verbose_name='Активен')),
                ('is_template', models.BooleanField(default=False, help_text='Шаблон для переиспользования', verbose_name='Шаблон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grades', models.ManyToManyField(blank=True, help_text='Грейды (если пусто - все)', to='finance.grade', verbose_name='Грейды')),
                ('position_types', models.ManyToManyField(blank=True, help_text='Типы позиций (если пусто - все)', to='hiring_plan.positiontype', verbose_name='Типы позиций')),
            ],
            options={
                'verbose_name': 'Блок KPI/OKR для плана',
                'verbose_name_plural': 'Блоки KPI/OKR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='hiringplanposition',
            name='applied_kpi_okr_blocks',
            field=models.ManyToManyField(blank=True, help_text='Блоки KPI/OKR, примененные к позиции', related_name='positions', to='hiring_plan.plankpiokrblock', verbose_name='Примененные блоки KPI/OKR'),
        ),
        migrations.AddField(
            model_name='positionkpiokr',
            name='plan_kpi_okr_block',
            field=models.ForeignKey(blank=True, help_text='Блок KPI/OKR для группового применения', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.plankpiokrblock', verbose_name='Блок KPI/OKR'),
        ),
        migrations.AlterUniqueTogether(
            name='positionkpiokr',
            unique_together={('plan_kpi_okr_block', 'period_start'), ('vacancy', 'grade', 'metric_type', 'period_start'), ('vacancy', 'metric_type', 'period_start')},
        ),
        migrations.RemoveField(
            model_name='positionsla',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='positionkpiokr',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='positionkpiokr',
            name='sla_comparison',
        ),
    ]
