# Generated by Django 5.2.5 on 2025-10-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0004_alter_positionsla_options_and_more'),
        ('vacancies', '0018_vacancy_tech_invite_text_vacancy_tech_invite_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positionsla',
            unique_together={('vacancy', 'grade')},
        ),
    ]
