# Generated by Django 5.2.5 on 2025-10-24 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0008_delete_positionsla'),
        ('vacancies', '0018_vacancy_tech_invite_text_vacancy_tech_invite_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_period', models.CharField(choices=[('next_month', 'Следующий месяц'), ('next_quarter', 'Следующий квартал'), ('next_year', 'Следующий год')], max_length=20, verbose_name='Период прогноза')),
                ('forecast_start', models.DateField(verbose_name='Начало прогнозного периода')),
                ('forecast_end', models.DateField(verbose_name='Конец прогнозного периода')),
                ('project', models.CharField(blank=True, max_length=200, verbose_name='Проект')),
                ('forecasted_demand', models.PositiveIntegerField(help_text='Ожидаемое количество заявок', verbose_name='Прогнозируемая потребность')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Уверенность в прогнозе (0-100%)', max_digits=5, verbose_name='Уровень уверенности (%)')),
                ('based_on_history', models.BooleanField(default=True, help_text='Прогноз основан на исторических данных', verbose_name='На основе истории')),
                ('seasonality_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Коэффициент сезонности (1.0 = нормально)', max_digits=5, verbose_name='Фактор сезонности')),
                ('growth_factor', models.DecimalField(decimal_places=2, default=1.0, help_text='Коэффициент роста команды', max_digits=5, verbose_name='Фактор роста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Прогноз потребности',
                'verbose_name_plural': 'Прогнозы потребности',
                'ordering': ['-forecast_start'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('active_requests_count', models.PositiveIntegerField(default=0, help_text='Текущее количество заявок в работе', verbose_name='Активных заявок')),
                ('planned_requests_count', models.PositiveIntegerField(default=0, help_text='Заявки, которые скоро начнутся', verbose_name='Запланировано заявок')),
                ('max_capacity', models.PositiveIntegerField(default=10, help_text='Максимальное количество заявок одновременно', verbose_name='Максимальная мощность')),
                ('available_capacity', models.PositiveIntegerField(default=0, help_text='Свободные слоты для новых заявок', verbose_name='Доступная мощность')),
                ('capacity_utilization', models.DecimalField(decimal_places=2, default=0, help_text='Процент использования мощности', max_digits=5, verbose_name='Загрузка (%)')),
                ('avg_time_per_request', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Среднее время на заявку (дни)')),
                ('closed_requests_count', models.PositiveIntegerField(default=0, verbose_name='Закрыто заявок за период')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Успешность закрытия (%)')),
                ('is_overloaded', models.BooleanField(default=False, help_text='Загрузка > 90%', verbose_name='Перегружен')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_plans', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
            ],
            options={
                'verbose_name': 'Мощность рекрутера',
                'verbose_name_plural': 'Мощности рекрутеров',
                'ordering': ['-period_start', 'recruiter'],
                'unique_together': {('recruiter', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='RecruitmentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Неделя'), ('monthly', 'Месяц'), ('quarterly', 'Квартал'), ('yearly', 'Год'), ('custom', 'Произвольный')], max_length=20, verbose_name='Тип периода')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('project', models.CharField(blank=True, max_length=200, verbose_name='Проект')),
                ('avg_time_to_fill', models.DecimalField(decimal_places=2, default=0, help_text='Среднее время от открытия до закрытия заявки', max_digits=6, verbose_name='Средний Time-to-Fill (дни)')),
                ('median_time_to_fill', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Медианный Time-to-Fill (дни)')),
                ('avg_time_to_hire', models.DecimalField(decimal_places=2, default=0, help_text='Среднее время от первого контакта до оффера', max_digits=6, verbose_name='Средний Time-to-Hire (дни)')),
                ('hires_count', models.PositiveIntegerField(default=0, verbose_name='Количество найма за период')),
                ('hiring_velocity_weekly', models.DecimalField(decimal_places=2, default=0, help_text='Количество закрытий в неделю', max_digits=6, verbose_name='Скорость найма (hires/week)')),
                ('avg_days_behind_schedule', models.DecimalField(decimal_places=2, default=0, help_text='Среднее количество дней просрочки для закрытых заявок', max_digits=6, verbose_name='Среднее отставание от графика (дни)')),
                ('overdue_requests_count', models.PositiveIntegerField(default=0, verbose_name='Количество просроченных заявок')),
                ('sla_compliance_rate', models.DecimalField(decimal_places=2, default=0, help_text='% заявок, закрытых в срок по SLA', max_digits=5, verbose_name='SLA Compliance (%)')),
                ('total_requests', models.PositiveIntegerField(default=0, verbose_name='Всего заявок за период')),
                ('closed_requests', models.PositiveIntegerField(default=0, verbose_name='Закрыто заявок')),
                ('in_progress_requests', models.PositiveIntegerField(default=0, verbose_name='В процессе')),
                ('cancelled_requests', models.PositiveIntegerField(default=0, verbose_name='Отменено')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Рассчитано')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд (если метрика для конкретного)')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия (если метрика для конкретной)')),
            ],
            options={
                'verbose_name': 'Метрики найма',
                'verbose_name_plural': 'Метрики найма',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='hiring_plan_period__47950c_idx'), models.Index(fields=['vacancy', 'grade'], name='hiring_plan_vacancy_87e5be_idx')],
                'unique_together': {('period_type', 'period_start', 'vacancy', 'grade', 'project')},
            },
        ),
    ]
