# Generated by Django 5.2.5 on 2025-10-24 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0009_demandforecast_recruitercapacity_recruitmentmetrics'),
        ('vacancies', '0019_alter_vacancy_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hiringrequest',
            name='hiring_plan_deadlin_e91786_idx',
        ),
        migrations.RemoveField(
            model_name='hiringrequest',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='opening_reason',
            field=models.CharField(choices=[('planned', 'Плановая'), ('new_position', 'Новая'), ('replacement', 'Замена')], default='new_position', max_length=30, verbose_name='Причина открытия'),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В процессе'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='planned', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='hiringrequest',
            index=models.Index(fields=['opening_date'], name='hiring_plan_opening_dd09a8_idx'),
        ),
    ]
