# Generated by Django 4.2.16 on 2025-10-26 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hiring_plan', '0017_add_closed_by_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='recruiter',
            field=models.ForeignKey(blank=True, help_text='Ответственный рекрутер за данную заявку', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер'),
        ),
        migrations.CreateModel(
            name='RecruiterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Назначен')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Снят с заявки')),
                ('is_active', models.BooleanField(default=True, help_text='Активно ли назначение', verbose_name='Активно')),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_assignments', to='hiring_plan.hiringrequest', verbose_name='Заявка')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
            ],
            options={
                'verbose_name': 'Назначение рекрутера',
                'verbose_name_plural': 'Назначения рекрутеров',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
