# Generated by Django 4.2.16 on 2025-10-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0018_hiringrequest_recruiter_recruiterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Дата, когда специалист вышел на работу (для расчета time2hire)', null=True, verbose_name='Дата выхода специалиста'),
        ),
    ]
