# Generated by Django 5.2.5 on 2025-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0019_hiringrequest_hire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrequest',
            name='opening_date',
            field=models.DateField(blank=True, help_text='Может быть в будущем или прошлом', null=True, verbose_name='Дата открытия вакансии'),
        ),
    ]
