# Generated by Django 5.2.6 on 2025-09-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickupsettings',
            name='api_token',
        ),
    ]
