# Generated by Django 5.2.6 on 2025-09-15 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clickup_int', '0005_auto_20250915_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickUpBulkImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('completed', 'Завершен'), ('failed', 'Ошибка'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='Всего задач')),
                ('processed_tasks', models.PositiveIntegerField(default=0, verbose_name='Обработано задач')),
                ('successful_tasks', models.PositiveIntegerField(default=0, verbose_name='Успешно импортировано')),
                ('failed_tasks', models.PositiveIntegerField(default=0, verbose_name='Неудачных импортов')),
                ('failed_task_ids', models.JSONField(blank=True, default=list, help_text='Список ID задач, которые не удалось импортировать', verbose_name='ID неудачных задач')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID задачи Celery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickup_bulk_imports', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Массовый импорт ClickUp',
                'verbose_name_plural': 'Массовые импорты ClickUp',
                'db_table': 'clickup_bulk_imports',
                'ordering': ['-created_at'],
            },
        ),
    ]
