# Generated by Django 4.2.16 on 2025-10-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0008_clickupbulkimport_huntflow_vacancy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickupbulkimport',
            name='include_comments',
            field=models.BooleanField(default=True, help_text='Если отмечено, комментарии из ClickUp будут переданы в Huntflow', verbose_name='Передавать комментарии в Huntflow'),
        ),
    ]
