# Generated by Django 5.2.6 on 2025-09-08 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0002_googlecalendarevent_attendees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_url', models.URLField(help_text='Ссылка на кандидата в Huntflow', verbose_name='Ссылка на кандидата')),
                ('candidate_id', models.CharField(blank=True, max_length=50, verbose_name='ID кандидата')),
                ('candidate_name', models.CharField(blank=True, max_length=255, verbose_name='Имя кандидата')),
                ('candidate_grade', models.CharField(blank=True, max_length=100, verbose_name='Уровень кандидата')),
                ('vacancy_id', models.CharField(blank=True, max_length=50, verbose_name='ID вакансии')),
                ('vacancy_title', models.CharField(blank=True, max_length=255, verbose_name='Название вакансии')),
                ('interview_datetime', models.DateTimeField(verbose_name='Дата и время интервью')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('google_drive_folder_id', models.CharField(blank=True, max_length=255, verbose_name='ID папки в Google Drive')),
                ('google_drive_file_id', models.CharField(blank=True, max_length=255, verbose_name='ID файла scorecard в Google Drive')),
                ('google_drive_file_url', models.URLField(blank=True, verbose_name='Ссылка на scorecard файл')),
                ('scorecard_template_url', models.URLField(blank=True, help_text='Ссылка на шаблон scorecard для вакансии', verbose_name='Ссылка на шаблон scorecard')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Инвайт',
                'verbose_name_plural': 'Инвайты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_sync_calendar', models.BooleanField(default=False, verbose_name='Автоматическая синхронизация календаря')),
                ('auto_sync_drive', models.BooleanField(default=False, verbose_name='Автоматическая синхронизация Drive')),
                ('sync_interval', models.IntegerField(default=60, help_text='Интервал синхронизации в минутах', verbose_name='Интервал синхронизации (минуты)')),
                ('max_events', models.IntegerField(default=100, help_text='Максимальное количество событий для синхронизации', verbose_name='Максимум событий')),
                ('max_files', models.IntegerField(default=100, help_text='Максимальное количество файлов для синхронизации', verbose_name='Максимум файлов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки синхронизации',
                'verbose_name_plural': 'Настройки синхронизации',
            },
        ),
    ]
