# Generated by Django 5.2.5 on 2025-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0006_invite_calendar_event_id_invite_calendar_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='google_meet_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на Google Meet'),
        ),
    ]
