# Generated by Django 5.2.5 on 2025-09-11 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0007_invite_google_meet_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_week_prefix', models.CharField(blank=True, help_text='Дополнительный текст, добавляемый перед слотами текущей недели при копировании', max_length=200, verbose_name='Текст перед слотами текущей недели')),
                ('next_week_prefix', models.CharField(blank=True, help_text='Дополнительный текст, добавляемый перед слотами следующей недели при копировании', max_length=200, verbose_name='Текст перед слотами следующей недели')),
                ('all_slots_prefix', models.CharField(blank=True, help_text='Дополнительный текст, добавляемый в начало при копировании всех слотов', max_length=200, verbose_name='Текст перед всеми слотами')),
                ('separator_text', models.CharField(default='---', help_text='Текст, который разделяет текущую и следующую неделю при копировании всех слотов', max_length=50, verbose_name='Разделитель между неделями')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slots_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки слотов',
                'verbose_name_plural': 'Настройки слотов',
            },
        ),
    ]
