# Generated by Django 5.2.5 on 2025-09-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0008_slotssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='gemini_additional_info',
            field=models.TextField(blank=True, help_text='Дополнительная информация для кандидата от Gemini AI', verbose_name='Дополнительная информация от Gemini'),
        ),
        migrations.AddField(
            model_name='invite',
            name='gemini_invitation_text',
            field=models.TextField(blank=True, help_text='Текст приглашения, сгенерированный Gemini AI', verbose_name='Текст приглашения от Gemini'),
        ),
        migrations.AddField(
            model_name='invite',
            name='gemini_meeting_link',
            field=models.URLField(blank=True, help_text='Ссылка на Google Meet, предложенная Gemini AI', verbose_name='Ссылка на встречу от Gemini'),
        ),
        migrations.AddField(
            model_name='invite',
            name='gemini_recruiter_notes',
            field=models.TextField(blank=True, help_text='Заметки для рекрутера, сгенерированные Gemini AI', verbose_name='Заметки для рекрутера от Gemini'),
        ),
        migrations.AddField(
            model_name='invite',
            name='gemini_suggested_datetime',
            field=models.CharField(blank=True, help_text='Предложенное время интервью от Gemini AI', max_length=50, verbose_name='Предложенное время от Gemini'),
        ),
    ]
