# Generated by Django 5.2.5 on 2025-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0010_invite_original_form_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='gemini_additional_info',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='gemini_invitation_text',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='gemini_meeting_link',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='gemini_recruiter_notes',
        ),
        migrations.AlterField(
            model_name='invite',
            name='gemini_suggested_datetime',
            field=models.CharField(blank=True, help_text='Время интервью, определенное Gemini AI на основе анализа исходного текста и слотов', max_length=50, verbose_name='Предложенное время от Gemini'),
        ),
    ]
