# Generated by Django 5.2.5 on 2025-10-14 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0018_invite_multiple_slots_data'),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE google_oauth_invite SET multiple_slots_data = '{}' WHERE multiple_slots_data IS NULL;",
            reverse_sql="UPDATE google_oauth_invite SET multiple_slots_data = NULL WHERE multiple_slots_data = '{}';"
        ),
    ]
