# Generated by Django 5.2.5 on 2025-10-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0019_auto_20251015_0112'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE google_oauth_invite DROP COLUMN multiple_slots_data;",
            reverse_sql="ALTER TABLE google_oauth_invite ADD COLUMN multiple_slots_data TEXT DEFAULT '{}';"
        ),
    ]
