# Generated by Django 5.2.5 on 2025-10-22 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0022_remove_invite_multiple_slots_data'),
        ('vacancies', '0015_scorecardupdatehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='vacancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='vacancies.vacancy', verbose_name='Вакансия'),
        ),
    ]
