# Generated by Django 5.2.5 on 2025-10-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0024_remove_invite_multiple_slots_data_and_more'),
    ]

    operations = [
        # Поле multiple_slots_data уже удалено из модели, операция не нужна
        migrations.AddField(
            model_name='invite',
            name='user_email',
            field=models.EmailField(blank=True, help_text='Email авторизованного пользователя, создавшего инвайт', max_length=254, verbose_name='Email пользователя'),
        ),
    ]
