# Generated by Django 5.2.5 on 2025-10-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_oauth', '0026_merge_20251022_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='multiple_slots_data',
        ),
    ]
