# Generated by Django 5.2.6 on 2025-09-05 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0003_alter_interviewrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewrule',
            name='allow_holiday_interviews',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='allow_weekend_interviews',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='require_calendar_link',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='work_end_time',
        ),
        migrations.RemoveField(
            model_name='interviewrule',
            name='work_start_time',
        ),
    ]
