# Generated by Django 5.2.6 on 2025-09-15 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickUpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(help_text='Токен для доступа к ClickUp API', max_length=255, verbose_name='API токен ClickUp')),
                ('team_id', models.CharField(help_text='ID команды в ClickUp', max_length=100, verbose_name='ID команды')),
                ('space_id', models.CharField(help_text='ID пространства в ClickUp', max_length=100, verbose_name='ID пространства')),
                ('folder_id', models.CharField(blank=True, help_text='ID папки в ClickUp (опционально)', max_length=100, null=True, verbose_name='ID папки')),
                ('list_id', models.CharField(help_text='ID списка задач в ClickUp', max_length=100, verbose_name='ID списка')),
                ('auto_sync', models.BooleanField(default=True, help_text='Автоматически синхронизировать задачи', verbose_name='Автоматическая синхронизация')),
                ('sync_interval', models.PositiveIntegerField(default=30, help_text='Интервал автоматической синхронизации в минутах', verbose_name='Интервал синхронизации (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clickup_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки ClickUp',
                'verbose_name_plural': 'Настройки ClickUp',
                'db_table': 'clickup_settings',
            },
        ),
        migrations.CreateModel(
            name='ClickUpSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('partial', 'Частично')], max_length=20, verbose_name='Статус синхронизации')),
                ('tasks_processed', models.PositiveIntegerField(default=0, verbose_name='Обработано задач')),
                ('tasks_created', models.PositiveIntegerField(default=0, verbose_name='Создано задач')),
                ('tasks_updated', models.PositiveIntegerField(default=0, verbose_name='Обновлено задач')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('sync_duration', models.FloatField(blank=True, null=True, verbose_name='Длительность синхронизации (секунды)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время синхронизации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickup_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог синхронизации ClickUp',
                'verbose_name_plural': 'Логи синхронизации ClickUp',
                'db_table': 'clickup_sync_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(help_text='Уникальный ID задачи в ClickUp', max_length=100, unique=True, verbose_name='ID задачи')),
                ('name', models.CharField(max_length=500, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание задачи')),
                ('status', models.CharField(max_length=100, verbose_name='Статус задачи')),
                ('priority', models.CharField(blank=True, max_length=50, verbose_name='Приоритет')),
                ('date_created', models.DateTimeField(verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(verbose_name='Дата обновления')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('url', models.URLField(verbose_name='Ссылка на задачу')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Список вложений в формате JSON', verbose_name='Вложения')),
                ('assignees', models.JSONField(blank=True, default=list, help_text='Список исполнителей в формате JSON', verbose_name='Исполнители')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Список тегов в формате JSON', verbose_name='Теги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в системе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в системе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clickup_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача ClickUp',
                'verbose_name_plural': 'Задачи ClickUp',
                'db_table': 'clickup_tasks',
                'ordering': ['-date_updated'],
            },
        ),
    ]
