# Generated by Django 5.2.6 on 2025-09-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0002_remove_clickupsettings_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickuptask',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='clickuptask',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
