# Generated by Django 5.2.5 on 2025-09-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0006_auto_20250915_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickupbulkimport',
            name='status',
            field=models.CharField(
                choices=[
                    ('running', 'Выполняется'),
                    ('completed', 'Завершен'),
                    ('failed', 'Ошибка'),
                    ('cancelled', 'Отменен'),
                    ('stopped', 'Остановлен')
                ],
                default='running',
                max_length=20,
                verbose_name='Статус'
            ),
        ),
    ]
