# Generated by Django 4.2.16 on 2025-09-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0007_auto_20250916_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickupbulkimport',
            name='huntflow_vacancy_id',
            field=models.IntegerField(blank=True, help_text='ID вакансии в Huntflow, к которой будут привязаны импортированные кандидаты', null=True, verbose_name='ID вакансии в Huntflow'),
        ),
    ]
