# Generated by Django 4.2.16 on 2025-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickup_int', '0009_clickupbulkimport_include_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickupsettings',
            name='huntflow_filter',
            field=models.CharField(choices=[('all', 'Все задачи'), ('with_huntflow', 'Только с тегом huntflow'), ('without_huntflow', 'Только без тега huntflow')], default='all', help_text='Выберите, какие задачи синхронизировать по тегу huntflow', max_length=20, verbose_name='Фильтр по тегу huntflow'),
        ),
    ]
