# Generated by Cursor on 2026-01-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huntflow', '0002_add_hh_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInHuntflowLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(max_length=500, verbose_name='LinkedIn URL')),
                ('account_id', models.IntegerField(verbose_name='Huntflow account_id')),
                ('applicant_id', models.IntegerField(verbose_name='Huntflow applicant_id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_huntflow_links', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка LinkedIn↔Huntflow',
                'verbose_name_plural': 'Связки LinkedIn↔Huntflow',
                'unique_together': {('user', 'linkedin_url')},
            },
        ),
        migrations.AddIndex(
            model_name='linkedinhuntflowlink',
            index=models.Index(fields=['user', 'linkedin_url'], name='huntflow_li_user_li_8fa0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='linkedinhuntflowlink',
            index=models.Index(fields=['user', 'account_id', 'applicant_id'], name='huntflow_li_user_ac_b6ed03_idx'),
        ),
    ]

