# Generated by Cursor on 2026-01-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("huntflow", "0003_linkedin_huntflow_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkedinhuntflowlink",
            name="target_url",
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name="Ссылка на кандидата (Huntflow/HRHelper)"),
        ),
        migrations.AlterField(
            model_name="linkedinhuntflowlink",
            name="account_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Huntflow account_id"),
        ),
        migrations.AlterField(
            model_name="linkedinhuntflowlink",
            name="applicant_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Huntflow applicant_id"),
        ),
    ]

