# Generated by Django 5.2.5 on 2026-01-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntflow', '0005_linkedin_thread_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinhuntflowlink',
            name='vacancy_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Huntflow vacancy_id'),
        ),
    ]
