# Generated by Django 5.2.5 on 2025-12-13 03:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HHRUAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Токен доступа для работы с API', verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, help_text='Токен для обновления access_token', null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(help_text='Время истечения токена доступа', verbose_name='Токен истекает')),
                ('hh_user_id', models.CharField(help_text='Уникальный идентификатор пользователя на HH.ru', max_length=50, unique=True, verbose_name='HH User ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('is_employer', models.BooleanField(default=False, help_text='Является ли пользователь работодателем', verbose_name='Работодатель')),
                ('is_admin', models.BooleanField(default=False, help_text='Является ли пользователь администратором аккаунта работодателя', verbose_name='Администратор')),
                ('profile_data', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные профиля из HH.ru API', verbose_name='Данные профиля')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hhru_account', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'HH.ru аккаунт',
                'verbose_name_plural': 'HH.ru аккаунты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HHRUConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(help_text='Идентификатор клиента OAuth приложения', max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(help_text='Секретный ключ OAuth приложения', max_length=200, verbose_name='Client Secret')),
                ('redirect_uri', models.URLField(help_text='URI для перенаправления после авторизации', verbose_name='Redirect URI')),
                ('name', models.CharField(help_text='Название конфигурации', max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать ли эту конфигурацию', verbose_name='Активна')),
                ('is_default', models.BooleanField(default=False, help_text='Конфигурация по умолчанию', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(blank=True, help_text='Если указан, настройки применяются только для этого пользователя', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hhru_configurations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Конфигурация HH.ru',
                'verbose_name_plural': 'Конфигурации HH.ru',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HHRUAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('GET', 'Получение данных'), ('POST', 'Создание'), ('PUT', 'Обновление'), ('PATCH', 'Частичное обновление'), ('DELETE', 'Удаление'), ('ERROR', 'Ошибка')], max_length=10, verbose_name='Тип операции')),
                ('endpoint', models.CharField(max_length=500, verbose_name='Эндпоинт')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='hhru.hhruaccount', verbose_name='HH.ru аккаунт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hhru_api_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог HH.ru API',
                'verbose_name_plural': 'Логи HH.ru API',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='hhru_hhruap_user_id_8b8c1d_idx'), models.Index(fields=['account', '-created_at'], name='hhru_hhruap_account_66ce4e_idx'), models.Index(fields=['log_type', '-created_at'], name='hhru_hhruap_log_typ_d5ad04_idx')],
            },
        ),
    ]
