# Generated by Django 5.2.6 on 2025-09-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clickup_api_key',
            field=models.CharField(blank=True, max_length=256, verbose_name='API ключ ClickUp'),
        ),
    ]
