# Generated by Django 4.2.16 on 2025-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_notion_integration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='huntflow_access_token',
            field=models.TextField(blank=True, help_text='Access token для Huntflow API', verbose_name='Access token для Huntflow API'),
        ),
        migrations.AddField(
            model_name='user',
            name='huntflow_refresh_expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения refresh token', null=True, verbose_name='Время истечения refresh token'),
        ),
        migrations.AddField(
            model_name='user',
            name='huntflow_refresh_token',
            field=models.TextField(blank=True, help_text='Refresh token для Huntflow API', verbose_name='Refresh token для Huntflow API'),
        ),
        migrations.AddField(
            model_name='user',
            name='huntflow_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Время истечения access token', null=True, verbose_name='Время истечения access token'),
        ),
    ]
