# Generated by Django 5.2.5 on 2025-10-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_huntflow_token_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interview_end_time',
            field=models.TimeField(default='18:00', help_text='Время окончания рабочего дня для планирования интервью', verbose_name='Конец рабочего времени для интервью'),
        ),
        migrations.AddField(
            model_name='user',
            name='interview_start_time',
            field=models.TimeField(default='09:00', help_text='Время начала рабочего дня для планирования интервью', verbose_name='Начало рабочего времени для интервью'),
        ),
    ]
