# Generated by Django 5.2.5 on 2025-10-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_interview_end_time_user_interview_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='huntflow_prod_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interviewer_calendar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_observer_active',
        ),
    ]
