# Generated by Django 5.2.5 on 2025-10-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_change_huntflow_tokens_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meeting_interval_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Время между встречами в минутах (кратно 5, от 0 до 60)', verbose_name='Время между встречами (минуты)'),
        ),
    ]
