# Generated by Django 5.2.5 on 2025-11-03 20:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
        ('finance', '0019_add_eur_currency_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_type', models.CharField(choices=[('office_format', 'Офисный формат'), ('finance', 'Финансы'), ('grade', 'Грейд'), ('general', 'Общий отказ')], help_text='Тип причины отказа', max_length=20, verbose_name='Тип отказа')),
                ('title', models.CharField(help_text='Краткое название шаблона для идентификации', max_length=200, verbose_name='Название шаблона')),
                ('message', models.TextField(help_text='Текст стандартного ответа для отказа', validators=[django.core.validators.MaxLengthValidator(5000)], verbose_name='Текст ответа')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли этот шаблон', verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('grade', models.ForeignKey(blank=True, help_text='Грейд (заполняется только для типа "Грейд")', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejection_templates', to='finance.grade', verbose_name='Грейд')),
            ],
            options={
                'verbose_name': 'Шаблон отказа',
                'verbose_name_plural': 'Шаблоны отказов',
                'ordering': ['rejection_type', 'grade__name', 'title'],
            },
        ),
    ]
