# Generated by Django 5.2.5 on 2025-10-24 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0005_alter_positionsla_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequestUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.PositiveIntegerField(help_text='Номер слота для headcount (1..N)', verbose_name='Номер слота')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В процессе'), ('hired', 'Нанят'), ('failed', 'Не удалось'), ('cancelled', 'Отменен')], default='open', help_text='Статус заявки', max_length=20, verbose_name='Статус')),
                ('sla_start_date', models.DateField(help_text='Дата начала отсчета SLA', verbose_name='Дата начала SLA')),
                ('sla_deadline', models.DateField(help_text='Дедлайн по SLA', verbose_name='Дедлайн SLA')),
                ('filled_date', models.DateField(blank=True, help_text='Дата закрытия заявки', null=True, verbose_name='Дата закрытия')),
                ('candidate_id', models.CharField(blank=True, help_text='ID найденного кандидата (из внешней системы)', max_length=100, verbose_name='ID кандидата')),
                ('candidate_name', models.CharField(blank=True, help_text='Имя найденного кандидата', max_length=255, verbose_name='Имя кандидата')),
                ('notes', models.TextField(blank=True, help_text='Дополнительные заметки по заявке', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grade', models.ForeignKey(help_text='Грейд специалиста', on_delete=django.db.models.deletion.PROTECT, to='finance.grade', verbose_name='Грейд')),
                ('position', models.ForeignKey(help_text='Позиция в плане найма', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='hiring_plan.hiringplanposition', verbose_name='Позиция')),
            ],
            options={
                'verbose_name': 'Заявка на специалиста',
                'verbose_name_plural': 'Заявки на специалистов',
                'ordering': ['position', 'grade', 'slot_number'],
                'unique_together': {('position', 'grade', 'slot_number')},
            },
        ),
    ]
