# Generated by Django 5.2.5 on 2025-10-24 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_eur_currency_support'),
        ('hiring_plan', '0006_hiringrequestunit'),
        ('vacancies', '0018_vacancy_tech_invite_text_vacancy_tech_invite_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancySLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_fill', models.PositiveIntegerField(help_text='Целевое время от открытия до закрытия вакансии', verbose_name='Time-to-Fill (дни)')),
                ('time_to_hire', models.PositiveIntegerField(help_text='Целевое время от первого контакта до оффера', verbose_name='Time-to-Hire (дни)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.grade', verbose_name='Грейд')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'SLA вакансии',
                'verbose_name_plural': 'SLA вакансий',
                'ordering': ['vacancy__name', 'grade__name'],
                'unique_together': {('vacancy', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=200, verbose_name='Проект')),
                ('priority', models.IntegerField(choices=[(1, 'Критический'), (2, 'Высокий'), (3, 'Средний'), (4, 'Низкий')], default=3, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('planned', 'Планируется'), ('in_progress', 'В процессе'), ('overdue', 'Просрочена'), ('cancelled', 'Отменена'), ('closed', 'Закрыта')], default='planned', max_length=20, verbose_name='Статус')),
                ('opening_reason', models.CharField(choices=[('replacement_army', 'Замена - армия'), ('replacement_fired', 'Замена - увольнение'), ('replacement_decree', 'Замена - декрет'), ('new_position', 'Новая позиция'), ('expansion', 'Расширение команды'), ('other', 'Другое')], max_length=30, verbose_name='Причина открытия')),
                ('opening_date', models.DateField(help_text='Может быть в будущем или прошлом', verbose_name='Дата открытия вакансии')),
                ('deadline', models.DateField(help_text='Целевая дата закрытия', verbose_name='Дедлайн')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('candidate_id', models.CharField(blank=True, help_text='ID найденного кандидата (из внешней системы)', max_length=100, verbose_name='ID кандидата')),
                ('candidate_name', models.CharField(blank=True, help_text='Имя найденного кандидата', max_length=255, verbose_name='Имя кандидата')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.grade', verbose_name='Грейд')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy', verbose_name='Вакансия')),
                ('sla', models.ForeignKey(blank=True, help_text='Автоматически определяется по Вакансия+Грейд', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hiring_plan.vacancysla', verbose_name='SLA')),
            ],
            options={
                'verbose_name': 'Заявка на найм',
                'verbose_name_plural': 'Заявки на найм',
                'ordering': ['-opening_date', 'priority'],
            },
        ),
        migrations.DeleteModel(
            name='HiringRequestUnit',
        ),
        migrations.AddIndex(
            model_name='hiringrequest',
            index=models.Index(fields=['status', 'opening_date'], name='hiring_plan_status_a7be1c_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringrequest',
            index=models.Index(fields=['vacancy', 'grade'], name='hiring_plan_vacancy_a3a139_idx'),
        ),
        migrations.AddIndex(
            model_name='hiringrequest',
            index=models.Index(fields=['deadline'], name='hiring_plan_deadlin_e91786_idx'),
        ),
    ]
