# Generated by Django 5.2.5 on 2025-10-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0007_vacancysla_hiringrequest_delete_hiringrequestunit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositionSLA',
        ),
    ]
