# Generated by Django 5.2.5 on 2025-10-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0010_remove_hiringrequest_hiring_plan_deadlin_e91786_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruitmentmetrics',
            name='avg_time_to_fill',
        ),
        migrations.RemoveField(
            model_name='recruitmentmetrics',
            name='median_time_to_fill',
        ),
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='avg_time_to_offer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Среднее время от открытия до предложения кандидату', max_digits=6, verbose_name='Средний Time-to-Offer (дни)'),
        ),
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='median_time_to_offer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Медианный Time-to-Offer (дни)'),
        ),
        migrations.AddField(
            model_name='vacancysla',
            name='time_to_offer',
            field=models.PositiveIntegerField(blank=True, help_text='Целевое время от открытия до предложения кандидату', null=True, verbose_name='Time-to-Offer (дни)'),
        ),
    ]
