# Generated by Django 5.2.5 on 2025-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0013_remove_time_to_fill_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='active_requests',
            field=models.PositiveIntegerField(default=0, help_text='Все заявки, которые не закрыты (in_progress + planned + cancelled)', verbose_name='Активные заявки'),
        ),
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='planned_requests',
            field=models.PositiveIntegerField(default=0, verbose_name='Планируемые'),
        ),
    ]
