# Generated by Django 5.2.5 on 2025-10-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0014_add_active_planned_requests_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='critical_requests_count',
            field=models.PositiveIntegerField(default=0, help_text='Активные заявки, которые просрочены', verbose_name='Критические'),
        ),
    ]
