# Generated by Django 5.2.5 on 2025-10-24 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0015_recruitmentmetrics_critical_requests_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntflowSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('huntflow_vacancy_id', models.IntegerField(db_index=True, verbose_name='ID вакансии в HuntFlow')),
                ('huntflow_applicant_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID кандидата в HuntFlow')),
                ('huntflow_log_id', models.IntegerField(blank=True, null=True, verbose_name='ID лога в HuntFlow')),
                ('entity_type', models.CharField(choices=[('vacancy', 'Вакансия'), ('applicant', 'Кандидат'), ('status_change', 'Изменение статуса')], max_length=20, verbose_name='Тип сущности')),
                ('huntflow_data', models.JSONField(help_text='Полные данные объекта из HuntFlow API', verbose_name='Данные из HuntFlow')),
                ('sync_status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=20, verbose_name='Статус синхронизации')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hiring_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huntflow_syncs', to='hiring_plan.hiringrequest', verbose_name='Заявка на найм')),
            ],
            options={
                'verbose_name': 'Синхронизация HuntFlow',
                'verbose_name_plural': 'Синхронизации HuntFlow',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['huntflow_vacancy_id', 'huntflow_applicant_id'], name='hiring_plan_huntflo_4e36d8_idx'), models.Index(fields=['sync_status'], name='hiring_plan_sync_st_487cd1_idx')],
            },
        ),
    ]
