# Generated by Django 5.2.5 on 2025-10-26 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring_plan', '0016_huntflowsync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='Рекрутер, который закрыл вакансию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Закрыто пользователем'),
        ),
    ]
