# Generated by Django 4.2.16 on 2025-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Название вашей компании', max_length=200, verbose_name='Название компании')),
                ('main_calendar_id', models.CharField(blank=True, help_text='ID календаря Google Calendar для компании', max_length=255, verbose_name='ID главного календаря')),
                ('org_structure', models.JSONField(blank=True, default=dict, help_text='Организационная структура компании в формате JSON', verbose_name='Оргструктура')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('auto', 'Автоматическая (по системе)')], default='auto', help_text='Цветовая тема интерфейса', max_length=10, verbose_name='Тема оформления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Настройки компании',
                'verbose_name_plural': 'Настройки компании',
            },
        ),
    ]
