# Generated by Django 5.2.5 on 2025-11-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_rejectiontemplate'),
        ('finance', '0019_add_eur_currency_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='active_grades',
            field=models.ManyToManyField(blank=True, help_text='Грейды, которые используются в вашей компании', related_name='company_settings', to='finance.grade', verbose_name='Активные грейды компании'),
        ),
    ]
