# Generated by Django 5.2.5 on 2025-11-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0003_companysettings_active_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectiontemplate',
            name='rejection_type',
            field=models.CharField(choices=[('office_format', 'Офисный формат'), ('finance', 'Финансы'), ('finance_more', 'Финансы - больше'), ('finance_less', 'Финансы - меньше'), ('grade', 'Грейд'), ('general', 'Общий отказ')], help_text='Тип причины отказа', max_length=20, verbose_name='Тип отказа'),
        ),
    ]
