# Generated by Django 5.2.5 on 2025-09-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='client_initialized',
            field=models.BooleanField(default=False, verbose_name='Клиент инициализирован'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='qr_login_active',
            field=models.BooleanField(default=False, verbose_name='QR логин активен'),
        ),
    ]
