# Generated by Django 5.2.5 on 2025-09-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_telegramuser_client_initialized_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramMessage',
        ),
    ]
