# Generated by Django 4.2.16 on 2025-10-07 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram', '0003_delete_telegrammessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='client_initialized',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_authorized',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='qr_login_active',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='session_name',
        ),
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя сессии')),
                ('session_data', models.TextField(blank=True, verbose_name='Данные сессии')),
                ('is_authorized', models.BooleanField(default=False, verbose_name='Авторизован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Telegram сессия',
                'verbose_name_plural': 'Telegram сессии',
                'ordering': ['-created_at'],
            },
        ),
    ]
