# Generated by Django 5.2.6 on 2025-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_int', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionpage',
            name='comments',
            field=models.JSONField(blank=True, default=list, verbose_name='Комментарии к странице'),
        ),
    ]
