# Generated by Django 4.2.16 on 2025-10-31 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion_int', '0002_notionpage_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='notionpage',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата интервью'),
        ),
        migrations.AddField(
            model_name='notionpage',
            name='interviewer',
            field=models.CharField(blank=True, help_text='Имя или email интервьюера', max_length=200, verbose_name='Интервьюер'),
        ),
    ]
