# Generated by Django 4.2.16 on 2025-10-31 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notion_int', '0003_notionpage_interview_date_notionpage_interviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionHuntflowMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_type', models.CharField(choices=[('language_vacancy', 'Language → Вакансия'), ('nuances_field', 'Нюансы → Поля кандидата'), ('status_status', 'Status Notion → Status Huntflow')], max_length=50, verbose_name='Тип связки')),
                ('notion_value', models.CharField(max_length=200, verbose_name='Значение из Notion')),
                ('huntflow_value', models.CharField(max_length=200, verbose_name='ID/Значение в Huntflow')),
                ('huntflow_account_id', models.IntegerField(blank=True, null=True, verbose_name='ID аккаунта Huntflow')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notion_huntflow_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связка Notion-Huntflow',
                'verbose_name_plural': 'Связки Notion-Huntflow',
                'db_table': 'notion_huntflow_mapping',
                'unique_together': {('user', 'mapping_type', 'notion_value')},
            },
        ),
    ]
