# Generated by Django 5.2.6 on 2025-09-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_salaryrange_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_belarus',
            field=models.URLField(blank=True, help_text='Ссылка на вакансию в Беларуси (например, rabota.by, jobs.tut.by)', verbose_name='Ссылка на вакансию (Беларусь)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_poland',
            field=models.URLField(blank=True, help_text='Ссылка на вакансию в Польше (например, pracuj.pl, nofluffjobs.com)', verbose_name='Ссылка на вакансию (Польша)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_remote',
            field=models.URLField(blank=True, help_text='Ссылка на удаленную вакансию (например, remote.co, weworkremotely.com)', verbose_name='Ссылка на вакансию (Remote)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_russia',
            field=models.URLField(blank=True, help_text='Ссылка на вакансию в России (например, hh.ru, superjob.ru)', verbose_name='Ссылка на вакансию (Россия)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_ukraine',
            field=models.URLField(blank=True, help_text='Ссылка на вакансию в Украине (например, work.ua, rabota.ua)', verbose_name='Ссылка на вакансию (Украина)'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_link_usa',
            field=models.URLField(blank=True, help_text='Ссылка на вакансию в США (например, linkedin.com, indeed.com)', verbose_name='Ссылка на вакансию (США)'),
        ),
    ]
