# Generated by Django 4.2.16 on 2025-09-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_remove_benchmarksettings_gemini_api_key'),
        ('vacancies', '0009_remove_vacancy_vacancy_link_remote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='available_grades',
            field=models.ManyToManyField(blank=True, help_text='Грейды, доступные для данной вакансии', related_name='available_vacancies', to='finance.grade', verbose_name='Доступные грейды'),
        ),
    ]
