# Generated by Django 5.2.6 on 2025-09-04 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntflowCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=255, unique=True, verbose_name='Ключ кэша')),
                ('data', models.JSONField(default=dict, verbose_name='Данные')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Обновлено')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Кэш Huntflow',
                'verbose_name_plural': 'Кэш Huntflow',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='HuntflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('GET', 'Получение данных'), ('POST', 'Создание'), ('PATCH', 'Обновление'), ('DELETE', 'Удаление'), ('ERROR', 'Ошибка')], max_length=10, verbose_name='Тип операции')),
                ('endpoint', models.CharField(max_length=500, verbose_name='Эндпоинт')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Код ответа')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Данные ответа')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог Huntflow',
                'verbose_name_plural': 'Логи Huntflow',
                'ordering': ('-created_at',),
            },
        ),
    ]
