# Generated by Django 5.2.5 on 2025-12-01 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('huntflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_response_id', models.CharField(help_text='Уникальный ID отклика на HH.ru', max_length=50, unique=True)),
                ('hh_vacancy_id', models.CharField(help_text='ID вакансии на HH.ru', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('location_id', models.CharField(blank=True, max_length=10)),
                ('experience_json', models.JSONField(default=list, help_text='История опыта работы в формате JSON')),
                ('skills_json', models.JSONField(default=list, help_text='Список навыков в формате JSON')),
                ('resume_text', models.TextField(blank=True)),
                ('hh_resume_url', models.URLField(blank=True)),
                ('hh_applicant_url', models.URLField(blank=True)),
                ('response_state', models.CharField(choices=[('invitation', 'Приглашение'), ('applied', 'Отклик'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('ignored', 'Проигнорировано')], default='applied', max_length=20)),
                ('import_status', models.CharField(choices=[('pending', 'Ожидание'), ('imported', 'Импортирован'), ('filtered', 'Отфильтрован'), ('error', 'Ошибка'), ('skipped', 'Пропущен')], default='pending', max_length=20)),
                ('filter_reasons', models.JSONField(default=list, help_text='Причины отфильтрации кандидата')),
                ('filter_score', models.FloatField(default=0.0, help_text='Оценка совпадения с фильтрами (0-100)')),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('vacancy_id', models.IntegerField(blank=True, null=True)),
                ('applicant_id', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='Полные данные из HH.ru API')),
                ('hh_created_at', models.DateTimeField(help_text='Когда был создан отклик на HH.ru')),
                ('hh_updated_at', models.DateTimeField(help_text='Когда отклик был обновлен на HH.ru')),
                ('imported_at', models.DateTimeField(auto_now_add=True, help_text='Когда отклик был импортирован в нашу систему')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Когда отклик был обработан', null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_hh_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hh_responses',
                'ordering': ['-hh_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HHSyncConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('vacancy_id', models.IntegerField()),
                ('hh_vacancy_id', models.CharField(max_length=50)),
                ('filters', models.JSONField(default=dict, help_text='\n        {\n            "allowed_locations": ["1", "2"],\n            "allowed_genders": ["any"],\n            "min_age": 18,\n            "max_age": 65,\n            "check_existing": true,\n            "min_experience_years": 1,\n            "max_experience_years": 50\n        }\n        ')),
                ('enabled', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('every_6_hours', 'Каждые 6 часов'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('manual', 'Ручная синхронизация')], default='daily', max_length=20)),
                ('total_responses_found', models.IntegerField(default=0)),
                ('total_responses_imported', models.IntegerField(default=0)),
                ('total_responses_filtered', models.IntegerField(default=0)),
                ('total_responses_errors', models.IntegerField(default=0)),
                ('auto_add_to_project', models.BooleanField(default=False, help_text='Автоматически добавлять импортированных кандидатов в проект')),
                ('project_id', models.IntegerField(blank=True, help_text='ID проекта для автоматического добавления', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Дата последней успешной синхронизации', null=True)),
                ('next_scheduled_sync', models.DateTimeField(blank=True, help_text='Дата следующей запланированной синхронизации', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hh_sync_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hh_sync_configurations',
                'unique_together': {('user', 'account_id', 'vacancy_id')},
            },
        ),
        migrations.CreateModel(
            name='HHSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Начато'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('failed', 'Ошибка'), ('partial', 'Частичное завершение')], default='started', max_length=20)),
                ('total_responses', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('filtered_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('sync_duration_seconds', models.IntegerField(blank=True, help_text='Длительность синхронизации в секундах', null=True)),
                ('filter_summary', models.JSONField(default=dict, help_text='Резюме фильтрации (reason: count)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='huntflow.hhsyncconfiguration')),
            ],
            options={
                'db_table': 'hh_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='HHFilterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_mismatch_count', models.IntegerField(default=0)),
                ('gender_mismatch_count', models.IntegerField(default=0)),
                ('age_mismatch_count', models.IntegerField(default=0)),
                ('experience_mismatch_count', models.IntegerField(default=0)),
                ('already_in_db_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('location_mismatch_percent', models.FloatField(default=0)),
                ('gender_mismatch_percent', models.FloatField(default=0)),
                ('age_mismatch_percent', models.FloatField(default=0)),
                ('experience_mismatch_percent', models.FloatField(default=0)),
                ('already_in_db_percent', models.FloatField(default=0)),
                ('other_percent', models.FloatField(default=0)),
                ('total_responses', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('rejection_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filter_statistics', to='huntflow.hhsyncconfiguration')),
            ],
            options={
                'db_table': 'hh_filter_statistics',
            },
        ),
        migrations.AddIndex(
            model_name='hhresponse',
            index=models.Index(fields=['account_id', 'vacancy_id'], name='hh_response_account_idx'),
        ),
        migrations.AddIndex(
            model_name='hhresponse',
            index=models.Index(fields=['import_status'], name='hh_response_import_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hhresponse',
            index=models.Index(fields=['hh_vacancy_id'], name='hh_response_hh_vacancy_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hhresponse',
            index=models.Index(fields=['email'], name='hh_response_email_idx'),
        ),
        migrations.AddIndex(
            model_name='hhresponse',
            index=models.Index(fields=['hh_response_id'], name='hh_response_hh_response_id_idx'),
        ),
        migrations.AddIndex(
            model_name='hhsyncconfiguration',
            index=models.Index(fields=['user', 'enabled'], name='hh_sync_config_user_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='hhsyncconfiguration',
            index=models.Index(fields=['sync_frequency'], name='hh_sync_config_sync_frequency_idx'),
        ),
        migrations.AddIndex(
            model_name='hhsynclog',
            index=models.Index(fields=['configuration', '-started_at'], name='hh_sync_logs_config_started_idx'),
        ),
        migrations.AddIndex(
            model_name='hhsynclog',
            index=models.Index(fields=['status'], name='hh_sync_logs_status_idx'),
        ),
    ]
