# Generated by Django 5.2.6 on 2025-09-04 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('BYN', 'BYN'), ('USD', 'USD'), ('PLN', 'PLN')], max_length=3, unique=True, verbose_name='Код валюты')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Курс BYN за 1 единицу')),
                ('scale', models.PositiveIntegerField(default=1, verbose_name='Масштаб')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получено')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название грейда')),
            ],
            options={
                'verbose_name': 'Грейд',
                'verbose_name_plural': 'Грейды',
                'ordering': ('name',),
            },
        ),
    ]
