# Generated by Django 5.2.5 on 2025-09-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_pln_taxes'),
        ('vacancies', '0007_alter_salaryrange_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_min_usd', models.DecimalField(decimal_places=2, help_text='Минимальная зарплата в долларах США', max_digits=10, verbose_name='Минимальная зарплата (USD)')),
                ('salary_max_usd', models.DecimalField(decimal_places=2, help_text='Максимальная зарплата в долларах США', max_digits=10, verbose_name='Максимальная зарплата (USD)')),
                ('salary_min_byn', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная зарплата в белорусских рублях', max_digits=12, null=True, verbose_name='Минимальная зарплата (BYN)')),
                ('salary_max_byn', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная зарплата в белорусских рублях', max_digits=12, null=True, verbose_name='Максимальная зарплата (BYN)')),
                ('salary_min_pln', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная зарплата в польских злотых', max_digits=12, null=True, verbose_name='Минимальная зарплата (PLN)')),
                ('salary_max_pln', models.DecimalField(blank=True, decimal_places=2, help_text='Максимальная зарплата в польских злотых', max_digits=12, null=True, verbose_name='Максимальная зарплата (PLN)')),
                ('is_active', models.BooleanField(default=True, help_text='Активна ли зарплатная вилка', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('grade', models.ForeignKey(help_text='Грейд для которого устанавливается зарплатная вилка', on_delete=django.db.models.deletion.CASCADE, related_name='finance_salary_ranges', to='finance.grade', verbose_name='Грейд')),
                ('vacancy', models.ForeignKey(help_text='Вакансия для которой устанавливается зарплатная вилка', on_delete=django.db.models.deletion.CASCADE, related_name='finance_salary_ranges', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Зарплатная вилка',
                'verbose_name_plural': 'Зарплатные вилки',
                'ordering': ['grade__name', 'salary_min_usd'],
                'unique_together': {('vacancy', 'grade')},
            },
        ),
    ]
