# Generated by Django 5.2.5 on 2025-09-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_add_salary_range_with_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHVacancyTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hh_id', models.CharField(help_text='Уникальный ID вакансии на hh.ru', max_length=50, unique=True, verbose_name='ID вакансии hh.ru')),
                ('raw_data', models.JSONField(help_text='JSON данные вакансии с API hh.ru', verbose_name='Сырые данные')),
                ('processed', models.BooleanField(default=False, help_text='Была ли вакансия отправлена на AI анализ', verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Временная вакансия hh.ru',
                'verbose_name_plural': 'Временные вакансии hh.ru',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='benchmark',
            name='hh_vacancy_id',
            field=models.CharField(blank=True, help_text='ID вакансии на hh.ru для предотвращения дублирования', max_length=50, null=True, unique=True, verbose_name='ID вакансии hh.ru'),
        ),
        migrations.AddField(
            model_name='benchmarksettings',
            name='hh_ai_prompt',
            field=models.TextField(default='', help_text='Специальный промпт для анализа вакансий с hh.ru', verbose_name='AI промпт для hh.ru'),
        ),
        migrations.AddField(
            model_name='benchmarksettings',
            name='hh_channel_active',
            field=models.BooleanField(default=True, help_text='Включить/отключить сбор вакансий с hh.ru', verbose_name='Канал hh.ru активен'),
        ),
        migrations.AddField(
            model_name='benchmarksettings',
            name='max_daily_hh_tasks',
            field=models.IntegerField(default=100, help_text='Лимит обработки вакансий с hh.ru за день', verbose_name='Максимум задач hh.ru в сутки'),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='domain',
            field=models.CharField(blank=True, choices=[('retail', 'Retail (Ритейл)'), ('fintech', 'Fintech (Финтех)'), ('gaming', 'Gaming (Гейминг)'), ('gambling', 'Gambling (Гемблинг)'), ('betting', 'Betting (Беттинг)'), ('medtech', 'Medtech/Healthtech (Медтех/Здравоохранение)'), ('telecom', 'Telecom (Телеком)'), ('edtech', 'Edtech (Образовательные технологии)'), ('agritech', 'Agritech (Агротех)'), ('proptech', 'Proptech (Недвижимость)'), ('legaltech', 'Legaltech (Юридические технологии)'), ('govtech', 'Govtech (Государственное управление)'), ('logistics', 'Logistics/Supply Chain (Логистика)'), ('foodtech', 'Foodtech (Пищевые технологии)'), ('insurtech', 'Insurtech (Страхование)'), ('martech', 'Martech (Маркетинговые технологии)'), ('adtech', 'Adtech (Рекламные технологии)'), ('cybersecurity', 'Cybersecurity (Кибербезопасность)'), ('cleantech', 'Cleantech/Sustaintech (Экологические технологии)'), ('hrtech', 'HRtech (Управление персоналом)'), ('traveltech', 'Traveltech (Туризм)'), ('sporttech', 'Sporttech (Спортивные технологии)'), ('entertainment', 'Entertainment (Развлечения)'), ('ecommerce', 'E-commerce (Электронная коммерция)'), ('blockchain', 'Blockchain/Crypto (Блокчейн и крипто)'), ('aiml', 'AI/ML (Искусственный интеллект и машинное обучение)'), ('iot', 'IoT (Интернет вещей)'), ('cloud', 'Cloud Computing (Облачные вычисления)')], help_text='Домен деятельности компании', max_length=20, null=True, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='ai_analysis_prompt',
            field=models.TextField(default='Ты - эксперт по анализу рынка труда и зарплат в IT-сфере. Проанализируй предоставленные данные о ВАКАНСИЯХ и верни структурированные данные для сохранения в базу данных.\n\nДАННЫЕ ДЛЯ АНАЛИЗА:\n{benchmark_data}\n\nКУРСЫ ВАЛЮТ ДЛЯ ПЕРЕСЧЕТА:\n{currency_rates}\n\nЗАДАЧИ:\n1. Проанализируй каждую ВАКАНСИЮ из данных\n2. Извлеки структурированную информацию для сохранения в базу\n3. Конвертируй все зарплаты в USD используя текущие курсы валют\n4. Определи рекомендуемые зарплатные диапазоны\n5. Выяви дополнительные данные (формат работы, компенсации, бенефиты, технологии, домен)\n\nФОРМАТ ОТВЕТА (строго JSON):\n{{\n    "analysis_metadata": {{\n        "analysis_date": "YYYY-MM-DD HH:MM:SS",\n        "total_processed": число,\n        "data_source": "источник данных",\n        "analysis_version": "3.0",\n        "currency_conversion_used": true\n    }},\n    "structured_benchmarks": [\n        {{\n            "type": "vacancy",\n            "vacancy_name": "название вакансии",\n            "grade": "грейд (Junior/Middle/Senior/Lead)",\n            "salary_from": число_в_USD,\n            "salary_to": число_в_USD,\n            "location": "локация (город, страна)",\n            "work_format": "remote/office/hybrid/all world",\n            "compensation": "дополнительные компенсации и бонусы",\n            "benefits": "социальные льготы и бенефиты",\n            "development": "возможности для развития и обучения",\n            "technologies": "используемые технологии и стеки",\n            "domain": "домен деятельности (retail/fintech/gaming/etc)",\n            "notes": "дополнительные заметки"\n        }}\n    ],\n    "recommended_ranges": {{\n        "grade_name": {{\n            "min_salary": число_в_USD,\n            "max_salary": число_в_USD,\n            "median_salary": число_в_USD,\n            "sample_size": число,\n            "confidence_level": "high/medium/low"\n        }}\n    }},\n    "market_insights": {{\n        "trends": ["тренд1", "тренд2"],\n        "in_demand_skills": ["навык1", "навык2"],\n        "salary_growth_rate": "процент",\n        "market_competitiveness": "высокая/средняя/низкая",\n        "geographic_variations": {{\n            "location": "разница в зарплатах в USD"\n        }},\n        "currency_analysis": {{\n            "conversion_accuracy": "высокая/средняя/низкая",\n            "exchange_rate_impact": "влияние курсов на зарплаты"\n        }}\n    }},\n    "recommendations": {{\n        "for_candidates": ["рекомендация1", "рекомендация2"],\n        "for_companies": ["рекомендация1", "рекомендация2"],\n        "salary_negotiation_tips": ["совет1", "совет2"]\n    }}\n}}\n\nВАЖНЫЕ ТРЕБОВАНИЯ:\n- АНАЛИЗИРУЙ ТОЛЬКО ВАКАНСИИ (type всегда "vacancy")\n- Все суммы ОБЯЗАТЕЛЬНО конвертируй в USD используя предоставленные курсы валют\n- Формат работы: только из списка (remote/office/hybrid/all world)\n- Домен: только из предустановленного списка (retail/fintech/gaming/gambling/betting/medtech/telecom/edtech/agritech/proptech/legaltech/govtech/logistics/foodtech/insurtech/martech/adtech/cybersecurity/cleantech/hrtech/traveltech/sporttech/entertainment/ecommerce/blockchain/aiml/iot/cloud)\n- Грейд: Junior/Middle/Senior/Lead\n- Поле salary_to ОБЯЗАТЕЛЬНО для вакансий (всегда указывай диапазон)\n- Технологии указывай через запятую\n- Локация в формате "Город, Страна" (например, "Минск, Беларусь")\n- При конвертации валют учитывай налоги и указывай в notes если необходимо\n\nПРАВИЛА КОНВЕРТАЦИИ ВАЛЮТ:\n- Если зарплата указана в BYN: умножь на курс BYN к USD\n- Если зарплата указана в EUR: умножь на курс EUR к USD  \n- Если зарплата указана в PLN: умножь на курс PLN к USD\n- Если зарплата указана в других валютах: используй ближайший курс или укажи в notes\n- Всегда указывай исходную валюту в notes при конвертации\n\nОтвечай ТОЛЬКО в формате JSON, без дополнительных комментариев.', help_text='Промпт для анализа данных о зарплатах через ИИ', verbose_name='Промпт для анализа данных через ИИ'),
        ),
    ]
