# Generated by Django 5.2.5 on 2025-09-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_update_ai_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='benchmarksettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, help_text='API ключ для интеграции с Google Gemini AI', max_length=200, null=True, verbose_name='API ключ Gemini'),
        ),
        migrations.AlterField(
            model_name='benchmarksettings',
            name='ai_analysis_prompt',
            field=models.TextField(default='Ты - эксперт по анализу рынка труда и зарплат в IT-сфере. Проанализируй предоставленные данные о ВАКАНСИЯХ и верни структурированные данные для сохранения в базу данных.\n\nДАННЫЕ ДЛЯ АНАЛИЗА:\n{benchmark_data}\n\nКУРСЫ ВАЛЮТ ДЛЯ ПЕРЕСЧЕТА:\n{currency_rates}\n\nЗАДАЧИ:\n1. Проанализируй каждую ВАКАНСИЮ из данных\n2. Извлеки структурированную информацию для сохранения в базу\n3. Конвертируй все зарплаты в USD используя текущие курсы валют\n4. Определи рекомендуемые зарплатные диапазоны\n5. Выяви дополнительные данные (формат работы, компенсации, бенефиты, технологии, домен)\n\nФОРМАТ ОТВЕТА (строго JSON):\n{{\n    "analysis_metadata": {{\n        "analysis_date": "YYYY-MM-DD HH:MM:SS",\n        "total_processed": число,\n        "data_source": "источник данных"\n    }},\n    "structured_benchmarks": [\n        {{\n            "type": "vacancy",\n            "vacancy_id": id_вакансии_из_hh_ru,\n            "vacancy_name": "название_соответствующей_в_базе_вакансии",\n            "grade": "грейд (Junior/Junior+/Middle/Middle+/Senior/Senior+/Lead/Head)",\n            "salary_from": число_в_USD,\n            "salary_to": число_в_USD,\n            "location": "локация (город, страна)",\n            "work_format": "remote/office/hybrid/all world",\n            "compensation": "дополнительные компенсации и бонусы",\n            "benefits": "социальные льготы и бенефиты",\n            "development": "возможности для развития и обучения",\n            "technologies": "используемые технологии и стеки",\n            "domain": "домен деятельности (retail/fintech/gaming/etc)",\n            "notes": "дополнительные заметки"\n        }}\n    ]\n}}\n\nВАЖНЫЕ ТРЕБОВАНИЯ:\n- АНАЛИЗИРУЙ ТОЛЬКО ВАКАНСИИ (type всегда "vacancy")\n- Все суммы ОБЯЗАТЕЛЬНО конвертируй в USD используя предоставленные курсы валют\n- Формат работы: только из списка (remote/office/hybrid/all world)\n- Домен: только из предустановленного списка (retail/fintech/gaming/gambling/betting/medtech/telecom/edtech/agritech/proptech/legaltech/govtech/logistics/foodtech/insurtech/martech/adtech/cybersecurity/cleantech/hrtech/traveltech/sporttech/entertainment/ecommerce/blockchain/aiml/iot/cloud)\n- Грейд: Junior/Junior+/Middle/Middle+/Senior/Senior+/Lead/Head\n- Поле salary_to ОБЯЗАТЕЛЬНО для вакансий (всегда указывай диапазон)\n- Технологии указывай через запятую\n- Локация в формате "Город, Страна" (например, "Минск, Беларусь")\n- При конвертации валют учитывай налоги и указывай в notes если необходимо\n\nПРАВИЛА КОНВЕРТАЦИИ ВАЛЮТ:\n- Если зарплата указана в BYN: умножь на курс BYN к USD\n- Если зарплата указана в PLN: умножь на курс PLN к USD\n- Если зарплата указана в других валютах: используй ближайший курс или укажи в notes\n- Всегда указывай исходную валюту в notes при конвертации\n\nОтвечай ТОЛЬКО в формате JSON, без дополнительных комментариев.', help_text='Промпт для анализа данных о зарплатах через ИИ', verbose_name='Промпт для анализа данных через ИИ'),
        ),
    ]
