# Generated by Django 4.2.16 on 2025-09-26 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_benchmarksettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='benchmarksettings',
            name='gemini_api_key',
        ),
    ]
