# Generated by Django 5.2.5 on 2025-12-12 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('company', 'По компании'), ('recruiter', 'По рекрутеру'), ('vacancy', 'По вакансии'), ('interviewer', 'По интервьюеру')], max_length=20, verbose_name='Тип отчета')),
                ('period', models.CharField(choices=[('daily', 'Ежедневная'), ('weekly', 'Понедельная'), ('monthly', 'Помесячная'), ('quarterly', 'Поквартальная'), ('yearly', 'Годовая')], max_length=20, verbose_name='Период')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('vacancy_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID вакансии')),
                ('interviewer_id', models.IntegerField(blank=True, null=True, verbose_name='ID интервьюера')),
                ('data', models.JSONField(default=dict, verbose_name='Данные отчета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('recruiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_caches', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
            ],
            options={
                'verbose_name': 'Кэш отчета',
                'verbose_name_plural': 'Кэш отчетов',
                'indexes': [models.Index(fields=['report_type', 'period', 'start_date', 'end_date'], name='reporting_r_report__51a5a6_idx')],
                'unique_together': {('report_type', 'period', 'start_date', 'end_date', 'recruiter', 'vacancy_id', 'interviewer_id')},
            },
        ),
    ]
