# Generated by Django 5.2.5 on 2025-12-12 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Уникальный идентификатор события в Google Calendar', max_length=255, unique=True, verbose_name='ID события')),
                ('title', models.CharField(max_length=500, verbose_name='Название события')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Вычисляется автоматически из start_time и end_time', verbose_name='Продолжительность (минуты)')),
                ('attendees', models.JSONField(blank=True, default=list, help_text='Список участников события в формате [{"email": "...", "name": "..."}]', verbose_name='Участники')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('location', models.CharField(blank=True, max_length=500, null=True, verbose_name='Местоположение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления записи')),
                ('google_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Время обновления в Google Calendar')),
                ('recruiter', models.ForeignKey(limit_choices_to={'groups__name': 'Рекрутер'}, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Рекрутер')),
            ],
            options={
                'verbose_name': 'Событие календаря',
                'verbose_name_plural': 'События календаря',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['recruiter', 'start_time'], name='reporting_c_recruit_1a9561_idx'), models.Index(fields=['start_time', 'end_time'], name='reporting_c_start_t_9824a3_idx'), models.Index(fields=['event_id'], name='reporting_c_event_i_914d22_idx')],
            },
        ),
    ]
